### ISSUE TITLE
PRE CONDIÇÕES

### ISSUE THREAD

**Issue by wfalcao** [islssa/SCM#1]
QUANTO A TELA INICIAL DEVEREMOS CRIAR UMA TELA PARA SELEÇÃO DO PLEITO OU VAMOS ACESSAR O SCM ATRAVÉS DE OUTRA APLICAÇÃO?

**Comment by danimendonca** [comment]
Existe uma funcionalidade (Consultar Pleito) onde todos os acessos, através de menu, serão disponibilizados a partir da consulta do Pleito.
Todos os casos de uso terão início a partir da seleção do Pleito no caso de uso CDU_SCM_036_Consultar Pleito.
