### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_ O sistema permite editar as funções eleitorais

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#10]
O sistema está permitindo mover as funções eleitorais Presidente, 1º
Mesário, 2º Mesário e 1º Secretário da coluna Selecionadas para a coluna Disponíveis.
A regra de negócio RN1 define : "...Como default o sistema deverá apresentar as seguintes funções:
• Presidente
• 1º Mesário
• 2º Mesário
• 1º Secretário
pré-selecionadas e sem a possibilidade de edição pelo ator."

Foi observado que quando o usuário altera essas funções e aciona o botão "Salvar" o sistema está apresentando a mensagem "As funções '1º Mesário', '1º Secretário', '2º Mesário', 'Presidente', são obrigatórias.", porém essa exceção/mensagem não está definida no caso de uso.

Nesse caso deve ser removida essa mensagem e apenas realizar o bloqueio dessas funções para não edição.

**Comment by jadossantos** [comment]
O componente do primefaces não tem tal comportamento. É necessário ajustar a documentação para uma nova solução, por exemplo, a implementada atualmente.

**Comment by marasb** [comment]
Vera.
Favor avaliar a possibilidade de alteração da documentação, para atender o comportamento atual do sistema.

**Comment by VeraNakamura** [comment]
Mara,
Assim que o Gestor chegar vou comunicar a impossibilidade de "travar" as funções.
Após alteração do documento aviso vocês.

Joel sugiro que para os próximos casos de uso, vocês façam uma análise antes, pois os Gestores estão solicitando vários comportamentos que eu não sei se os componentes permitem. Como exemplo: os Gestores estão solicitando que a ordenação de uma lista seja feita após o "click" na coluna que deseja ordenar.

**Comment by jadossantos** [comment]
Ok. Iremos melhorar esse processo.
