### ISSUE TITLE
CDU_SCM_007_Atribuir_Funcao_Eleitoral_a_Mesario - Ajuste do campo

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#100]
Ajuste da posição do campo [Local de Votação] . Alinhar com os demais titulos que apresetam na tela.

![a3](https://cloud.githubusercontent.com/assets/9218077/5542993/e6e042ec-8ad4-11e4-8702-981cbd298b20.jpg)

**Comment by halvesl** [comment]
corrigido. Aguardar próximo deploy.

**Comment by kleiberfaria** [comment]
Item verificado !
