### ISSUE TITLE
CDU_SCM_007_Atribuir_Funcao_Eleitoral_a_Mesario - Navegação menu e sub menuTravando 

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#101]
Prezados,

Ao selecionar qualquer funcionalidade na navegação superior e no sub menu de navegação do SCM, ocorre não constantante, a não resposta do click na funcionalidade. Gera um impacto no script de teste.

![navegacao_travando](https://cloud.githubusercontent.com/assets/9218077/5549675/f8e6f2be-8b75-11e4-93f6-596ae6fe2e92.jpg)

**Comment by halvesl** [comment]
Mesmo não constante, fiz vários testes e experimentos com o mesmo e não obtive o erro, aparentemente está tudo ok. Com isso, não consigo atuar nesse erro.

**Comment by kleiberfaria** [comment]
Item verificado !
