### ISSUE TITLE
CDU_SCM_007_Atribuir_Funcao_Eleitoral_a_Mesario - FA4 Promover Eleitor

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#102]
Prezados,

Conforme fluxo [ FA4 Promover eleitor ], ao iniciar o passo para a seleção do campo "Promoção" , para um eleitor atribuido, a  funcionalidade encontra-se ainda sem implementação para o mesmo. Sendo assim, não é possivel gerar script para a devida automação.

![fa4](https://cloud.githubusercontent.com/assets/9218077/5557865/0f5723e8-8cf7-11e4-8d80-f1543bcdd526.jpg)

![fa4_1](https://cloud.githubusercontent.com/assets/9218077/5557867/1632be98-8cf7-11e4-9cb9-9ca7f7e82c7f.jpg)

![222222](https://cloud.githubusercontent.com/assets/9218077/5558247/44ea4508-8d06-11e4-91aa-837df7006d54.jpg)

**Comment by halvesl** [comment]
Kleiber, de acordo com a RGN37 desse mesmo fluxo, para haver promoção o sistema necessita de informações que ainda não foram implementadas nessa iteração, sendo assim, não consigo executar esse fluxo e essa regra sem a consolidação dessas informações, nas quais, tudo indica que serão implementadas pelo CDU013 Gerenciar edital.

**Comment by kleiberfaria** [comment]
Conforme informação do desenvolvedor, fecho esse git pois será implementado em iterações futuras.
