### ISSUE TITLE
CDU_SCM_002_Gerenciar_Configuração_de_Mesa_Receptora_de_Votos - MRV

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#107]
Prezados,

Ao realizar o acesso na funcionalidade no menu Configurar [MRV], a aplicação apresenta a mensagem conforme o print em anexo.
![erro1](https://cloud.githubusercontent.com/assets/9218077/5719905/2fded302-9b04-11e4-8a93-7813f0e92731.jpg)

**Comment by saires** [comment]
Deve ser definido como essas FUNÇÕES OBRIGATÓRIAS serão previamente cadastradas. Isso atualmente está sendo feito através de um script. Lembrando que cada eleição poderá ter funções diferentes (RN1 e RN2).

**Comment by saires** [comment]
Para evitar esse problema, pedir para o leandro deixar o script de insert alinhado com os dados do pessoal do teste.

**Comment by jmatil** [comment]
Situação corrigida
