### ISSUE TITLE
CDU_SCM_005_Gerenciar_Criterio_Selecao_e_Base_de_Eleitores_Convocaveis - Posicionamento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#108]
Prezados,

Na tela de interface FA 2, "voluntário" na aplicação no ambiente de homologação, não esta com campo de seleção conforme o CDU. Conforme imagem em anexo, favor verificar o posicionamento dos campos.

![css](https://cloud.githubusercontent.com/assets/9218077/5800249/647da052-9fc3-11e4-8283-7ec92e20778b.jpg)

![css2](https://cloud.githubusercontent.com/assets/9218077/5800280/a92c230e-9fc3-11e4-8648-0d643d14af29.jpg)

**Comment by halvesl** [comment]
corrigido, favor aguardar próximo deploy!

**Comment by kleiberfaria** [comment]
Estarei verificando assim que for realizado o mesmo. Obrigado !

**Comment by saires** [comment]
Gentileza validar.

**Comment by jmatil** [comment]
Item validado
