### ISSUE TITLE
CDU_SCM_007_Atribuir_Funcao_Eleitoral_a_Mesario - Mensagem Duplicada

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#109]
Favor verificar a mensagem emitida pelo sistema ao simular o fluxo de exceção 3 - Eleitor atribuído a outra função eleitoral, pois a mensagem está duplicada.

![issue](https://cloud.githubusercontent.com/assets/6584772/5800700/53e0cb74-9fc9-11e4-83a4-b17d99fb4f09.png)

**Comment by halvesl** [comment]
corrigido!

**Comment by jmatil** [comment]
correção confirmada
