### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_Mensagem "Confirma operação" incorreta

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#11]
Ao realizar a configuração da MRV e acionar o botão "Salvar", foi observado que o sistema apresenta a mensagem "Confirma operação?", porém no caso de uso não está definido esse passo de apresentação dessa mensagem. Também não foi identificada essa mensagem no documento de mensagens.

**Comment by jadossantos** [comment]
Feito.

**Comment by marasb** [comment]
Defeito corrigido.
