### ISSUE TITLE
CDU_SCM_037_Consultar_Pleito_Eleitoral - Filtro de Pesquisa - Referente ao CDU 37

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#110]
Prezados,

Ao realizar uma pesquisa para se obter um filtro de um determinado número de identificação e ao acessar o campo "Pesquisar" a aplicação traz mais números de identificação e não apenas de uma determinada pesquisa.

![4342](https://cloud.githubusercontent.com/assets/9218077/5856402/223c23e4-a22a-11e4-9a94-fce8040efd9a.jpg)

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Correção confirmada
