### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Mensagem

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#111]
Favor verificar a mensagem que está sendo duplicada ao executar o fluxo FA5 - Alterar Quantitativo para a função administrador de prédio.

![issueh1](https://cloud.githubusercontent.com/assets/6584772/5856440/5c683742-a22a-11e4-89f5-20c99d9ee47d.png)

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Correção confirmada
