### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Consulta por função especial

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#112]
Prezados
favor verificar o bug na caixa de texto referente a função especial, pois digitei a função na caixa de texto com a acentuação referente a palavra, acionei a opção pesquisar e o sistema não encontrou o resultado que consta entre as funções, pois foi trocado automaticamente a acentuação fazendo com que a pesquisa não obtivesse resultado satisfatório. 
Obs.: 
1) A letra acentuada foi replicando a cada acionamento do botão pesquisar.
2) O sistema está duplicando as mensagens;

![issueh2](https://cloud.githubusercontent.com/assets/6584772/5858599/9ecd8e32-a23b-11e4-9bdb-545b2f6e7081.png)

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Confirmado a correção
