### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Quantidade por local de votação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#113]
Ao acionar o botão "Quantidade por Local de Votação" o sistema direciona o ator à tela de sistema disponíveis no Odin.
Obs.: A ação está sendo realizada utilizando o Município 57134 - JAGUARÉ

![issueh3](https://cloud.githubusercontent.com/assets/6584772/5859466/a4c8af00-a241-11e4-8ded-ac431b9d12d4.png)

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Correção confirmada
