### ISSUE TITLE
CDU_SCM_005_Gerenciar Criterio de Selecao e Base de Eleitores Convocaveis - Regra de apresentação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#114]
Favor verificar se os itens solicitados na documentação deverão aparecer ao acionar a opção "Selecionar Manualmente" ou serão apresentados somente após a realização da pesquisa.

![issueh6](https://cloud.githubusercontent.com/assets/6584772/5899049/8dac2668-a53d-11e4-99da-cb0e8f1637dd.png)

**Comment by halvesl** [comment]
De acordo com o Fluxo, será apresentada a lista de eleitores "pesquisados", e de acordo com a RN62, porém a mesma não especifica a forma com que a lista deveria ser apresentada. Por tanto, assumimos que essa lista será apresentada após a ação de pesquisa. Aí sim serão apresentados todos os eleitores pesquisados manualmente naquele instante.

**Comment by jmatil** [comment]
Issue compreendida.
