### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Atores

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#115]
Favor verificar o perfil de acesso exigido pela documentação

![issue1](https://cloud.githubusercontent.com/assets/6584772/6112577/713a3402-b078-11e4-8c2f-f9c1821c76c8.png)

**Comment by saires** [comment]
Controle de menu implementado.

**Comment by jmatil** [comment]
Implementação confirmada

![corrigido](https://cloud.githubusercontent.com/assets/6584772/6144963/0e056a4e-b1c4-11e4-8ef5-e23c7b6e8d66.png)
