### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Local de Votação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#116]
Verificar a ação do ícone de pesquisa do local de votação, pois está sem ação.
OBS: Verificar a situação, pois impacta na simulação da RN65
![issue2](https://cloud.githubusercontent.com/assets/6584772/6130551/e5a4f246-b12c-11e4-82e1-c6753f8b071e.png)

![issue31](https://cloud.githubusercontent.com/assets/6584772/6288814/bd60d3bc-b902-11e4-8217-ac86765a3da9.png)

**Comment by saires** [comment]
Corrigido. Favor realizar novo teste.

**Comment by jmatil** [comment]
Correção confirmada
