### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Campo "Número"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#118]
O campo Número não está sendo limpo ao ser acionado a opção "Limpar"

![issue4](https://cloud.githubusercontent.com/assets/6584772/6131216/8607f9f0-b131-11e4-9a5c-6954dd7cafdb.png)

**Comment by saires** [comment]
A ação do botão foi corrigida.

**Comment by jmatil** [comment]
Favor verificar novamente, pois até o momento não foi possível confirmar a correção realizada

**Comment by saires** [comment]
Faltava realizar deploy.

**Comment by jmatil** [comment]
Ação confirmada
