### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Quantidade de caracteres

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#119]
Verificar a quantidade de Caracteres exigidos para os campos "Seção" e "Inscrição"

![issue5](https://cloud.githubusercontent.com/assets/6584772/6131587/343eb458-b134-11e4-859a-c5cd08eae688.png)

**Comment by saires** [comment]
Mônica,
gentileza conduzir essa alteração em documentação. Encaminhei um e-mail com os comentários.

**Comment by monicaleite** [comment]
O caso de uso foi ajustado conforme a aplicação, já está atualizado no git.

**Comment by jmatil** [comment]
confirmado a correção na documentação atualizada.
