### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_ Erro tela inicial

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#12]
Ao selecionar a opção "Mesa Receptora de Votos" o sistema está apresentando inicialmente a tela de exclusão e não apresenta os campos UF, Zona Eleitoral, Pleito Eleitoral preenchidos.
O correto é aparecer a tela de inclusão primeiro com as informações  UF, Zona Eleitoral, Pleito Eleitoral preenchidas.

![erro_tela inicial](https://cloud.githubusercontent.com/assets/6304414/2607909/24e9f89e-bb64-11e3-840b-04b11a962f8c.jpg)

**Comment by jadossantos** [comment]
Os ambientes de desenvolvimento e teste estavam compartilhando o mesmo banco de dados.

**Comment by marasb** [comment]
Defeito corrigido.
