### ISSUE TITLE
CDU_SCM_037_Consultar_Pleito_Eleitoral - Filtro de Pesquisa - Menu Superior

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#120]
Prezados,

Conforme tela em anexo, o menu superior de navegação da aplicação SCM não está visivel após realizar o fluxo FB1. Consultar Pleito. O mesmo só é disponibilizados depois que é selecionado no menu "Selecionar Perfil"

![21](https://cloud.githubusercontent.com/assets/9218077/6131729/2a6427b4-b135-11e4-924e-173f786f0881.JPG)

**Comment by saires** [comment]
Aparição do menu corrigida.

**Comment by saires** [comment]
Gentileza validar.

**Comment by jmatil** [comment]
Ação validada.
