### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Descrição do Campo "Número"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#121]
Verificar se na citação da tabela de apresentação da tela há necessidade de disponibilidade do campo "Número", pois somente é citado na lista de resultado dos eleitores.

![issue6](https://cloud.githubusercontent.com/assets/6584772/6132448/c6ae1afe-b139-11e4-8b5f-b36a1ab9d61b.png)

**Comment by monicaleite** [comment]
Incluído o campo na descrição da tela conforme protótipo da documentação.

**Comment by jmatil** [comment]
Confirmado a inclusão com base na documentação disponibilizada no repositório GIT
