### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Campo Obrigatório

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#122]
O campo Município é de preenchimento obrigatório? Em caso positivo, favor verificar se há necessidade de inclusão ou adaptação em algum fluxo de Exceção.

![issue7](https://cloud.githubusercontent.com/assets/6584772/6132596/a10de5e4-b13a-11e4-9178-f3d85fd3cbdc.png)

**Comment by monicaleite** [comment]
Incluída obrigatoriedade para o campo Município e o fluxo de exceção FE9 referenciado no passo FB1.3. O git está atualizado.

**Comment by jmatil** [comment]
Confirmado a inclusão com base na documentação disponibilizada no repositório GIT
