### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Funções eleitorais "Pré-Requisito CDU007"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#123]
Verificar a disponibilidade das funções eleitorais disponibilizadas referentes ao caso de uso 007 - Atribuir função eleitoral à mesário.

![issue8](https://cloud.githubusercontent.com/assets/6584772/6133202/76c65c26-b13f-11e4-8a22-c74ae65de41f.png)

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Correção confirmada
![corrigido](https://cloud.githubusercontent.com/assets/6584772/6144932/caf7f9ce-b1c3-11e4-812e-a802de0120a8.png)
