### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - mensagem de alerta

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#124]
Verificar o comportamento do sistema para a situação relatada abaixo:
- Selecionar o campo: Seção;
- Pressionar a tecla: Alt + (nº 3 por três vezes);
- Acionar o botão: Consultar;
  Obs: A mesma situação ocorre na pesquisa do município e para os campo Número

![issue9](https://cloud.githubusercontent.com/assets/6584772/6133512/93a53a7c-b141-11e4-8ed6-263129754968.png)

**Comment by saires** [comment]
Esse erro é do componente do primefaces. Ele não trata todas as ações do usuário, como por exemplo a opção "colar" do botão direito do mouse. Para contornar essa situação seria necessário fluxos de exceção.

**Comment by monicaleite** [comment]
Sávio,

A regra informa que o campo permite apenas números, logo não deve passar esse erro, não é o caso de fazer exceção, visto que não é para permitir de forma alguma inserir letras.

**Comment by saires** [comment]
Corrigido. Favor realizar novo teste.

**Comment by jmatil** [comment]
Seguindo os passos anteriormente citados o erro ainda persiste
![issue30](https://cloud.githubusercontent.com/assets/6584772/6285532/15248f86-b8e4-11e4-96c8-99922b15feeb.png)

**Comment by jmatil** [comment]
Correção confirmada
