### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Funções especiais "Pré-Requisito CDU039"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#125]
Favor verificar o comportamento do sistema ao atribuir função Especial ao eleitor, pois é pré-requisito para esta iteração3. Segue imagem;

![issue10](https://cloud.githubusercontent.com/assets/6584772/6133714/0cde5b0c-b143-11e4-8d84-5b311b13e284.png)

**Comment by saires** [comment]
Realizar novo teste.

**Comment by jmatil** [comment]
Reteste realizado. Correção confirmada para o Ambiente (Integração)

![corrigido](https://cloud.githubusercontent.com/assets/6584772/6353353/9aaadab6-bc27-11e4-87f5-4938e72bbd8d.png)
