### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Atribuir Funções eleitorais "Pré-Requisito CDU007"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#126]
O sistema não está salvando as funções atribuidas ou não emite alguma mensagem de alerta indicando a impossibilidade.

![issue11](https://cloud.githubusercontent.com/assets/6584772/6149591/ed1200ea-b1f0-11e4-9f60-8a9a2bdeb016.png)

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Favor verificar, pois o erro persiste.

**Comment by saires** [comment]
Verificar novamente.

**Comment by jmatil** [comment]
Item verificado. Erro persiste

**Comment by saires** [comment]
Favor realizar novo teste.

**Comment by jmatil** [comment]
Correção confirmada
![corrigido](https://cloud.githubusercontent.com/assets/6584772/6353454/18a3e192-bc28-11e4-8ddd-ae5353f11a70.png)
