### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Atribuir Funções eleitorais "Pré-Requisito CDU007" - Pesquisa

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#127]
Favor verificar a realização da pesquisa do local de votação, pois está trazendo resultados desnecessários para realização da consulta. Segue imagem

![issue12](https://cloud.githubusercontent.com/assets/6584772/6149685/8c4716dc-b1f1-11e4-981a-48036fe3cab5.png)

**Comment by halvesl** [comment]
corrigido!

**Comment by jmatil** [comment]
Correção confirmada

![corrigido](https://cloud.githubusercontent.com/assets/6584772/6353505/87d0062c-bc28-11e4-8383-6c3264160c9c.png)
