### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - FE7 Exclusão de evento não permitido

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#128]
Este fluxo é chamado no FA2. Excluir Evento?

![issue14](https://cloud.githubusercontent.com/assets/6584772/6150971/cbbb4dee-b1f9-11e4-9a59-12fbc0b5ade9.png)

![issue13](https://cloud.githubusercontent.com/assets/6584772/6150957/b0893180-b1f9-11e4-95f8-f6614a58957a.png)

**Comment by monicaleite** [comment]
O fluxo FE7 foi inserido no passo FA2.3 do caso de uso e está atualizado no git.

**Comment by jmatil** [comment]
Confirmado a inclusão com base na documentação disponibilizada no repositório GIT
