### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Gerenciar Critério de Seleção / Pré-Requisito

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#129]
Verificar se na configuração de critérios "Estatísticas", a tabela contendo a quantidade de eleitores encontrados deverá conter a quantidade de eleitores ou se com o valor "zero" apresentado conforme imagem o resultado deverá ser apresentado.

![issue15](https://cloud.githubusercontent.com/assets/6584772/6151060/8f258272-b1fa-11e4-8bb3-886be9d431c8.png)

**Comment by halvesl** [comment]
corrigido!

**Comment by jmatil** [comment]
Correção confirmada
