### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_Erro tela de detalhe

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#13]
A tela de de consulta de configuração de MRV está totalmente divergente em termo de layout em relação a tela definida no caso de uso.

**Comment by jadossantos** [comment]
O padrão (css) do layout do sistema ainda não foi definido. Entramos em contato com o responsável da criação do CSS e estamos aguardando uma resposta. Iremos tratar isso como uma melhoria.

**Comment by marasb** [comment]
Esse bug será fechado, pois foi aberto um bug mais detalhado para esse item. (20)
