### ISSUE TITLE
CDU_SCM_040_Solicitar_e_Autorizar_Eleitor - Número do documento

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#130]
Prezados,

Ao inserir um "Número de Documento" qual alfa e númerico, a aplicação exibe a mensagem conforme print em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/6170423/d4873de4-b2bb-11e4-84b3-6161ebf8249c.png)

**Comment by halvesl** [comment]
corrigido!

**Comment by kleiberfaria** [comment]
Esse GIT foi corrigido e verificado, se tratando do erro relatado.
