### ISSUE TITLE
CDU_SCM_037_Consultar_Pleito_Eleitoral - Consultar Processo Eleitoral

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#131]
Prezados,

Ao realizar a consultar "Número de Identificação" conforme tela em anexo, o sistema apresenta a mensagen de erro. Já para no campo "Processo Eleitoral"  ao preencher o campo, o sistema deixa armazenado o que foi digitado anteriormente.

![1](https://cloud.githubusercontent.com/assets/9218077/6173206/6a4457fc-b2cd-11e4-81ee-409d22b1b838.jpg)

![2](https://cloud.githubusercontent.com/assets/9218077/6173214/6dc984a6-b2cd-11e4-863b-8d895e2d34b1.png)

**Comment by saires** [comment]
Esse erro é do componente do primefaces. Ele não trata todas as ações do usuário, como por exemplo a opção "colar" do botão direito do mouse, permitindo assim caracteres em campos não deveriam ter. Para contornar essa situação seria necessário fluxos de exceção.

**Comment by monicaleite** [comment]
Sávio, 

Esse erro deve ser tratado pela aplicação uma vez que a regra deixa claro que o campo é apenas numérico, não será criada uma exceção, pois não deve permitir caracteres.

**Comment by saires** [comment]
Corrigido. Favor realizar novo teste.

**Comment by kleiberfaria** [comment]
Item verificado !
