### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Campo "Número" - MRJ

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#132]
Preciso de auxílio para compreender a origem do campo "Número". Há um cadastro anterior que dever ser realizado para obtenção da consulta utilizando este campo?

![issue16](https://cloud.githubusercontent.com/assets/6584772/6187143/c17304be-b369-11e4-8a2f-230cd7757429.png)

**Comment by monicaleite** [comment]
Essa informação está sendo levantada com o gestor, assim que obtivermos uma resposta a documentação será atualizada.

**Comment by monicaleite** [comment]
Informação repassada pelo Leônidas. Esta informação vem da tabela admcad.MRJ. Verificar junto ao desenvolvimento o que será modificado no sistema.

**Comment by jmatil** [comment]
Sávio
Você tem conhecimento se algo deverá ser ou não implementado para obtermos resultados favoráveis?

**Comment by saires** [comment]
O UC07 (Atribuir função eleitoral a mesário) seria na teoria o responsável por cadastrar o número da MRJ. Porém esse UC não trata como essa informação será salva. Na última reunião foi definido de onde será extraído mas ainda falta definir como isso será feito no caso de uso.

**Comment by monicaleite** [comment]
Sávio,

Preciso que vc me oriente no que precisa ser mudado no caso de uso para que fique claro o entendimento sobre o campo número.

**Comment by monicaleite** [comment]
Vamos aguardar que o cliente identifique o problema e abra bugzilla para correção.

**Comment by jmatil** [comment]
O item foi implementado. Irei verificar se houve impacto após a atualização da fucionalidade.
