### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Inclusão e identificação dos itens

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#133]
Favor verificar a identificação e a necessidade de inclusão do campo destacados na imagem

![issue18](https://cloud.githubusercontent.com/assets/6584772/6264813/7a3b7f82-b80e-11e4-9842-10c44dcb5a08.png)

**Comment by saires** [comment]
Essas colunas são apresentadas apenas quando a pesquisa for feita pelo número da inscrição. Verificar FB1 e FA1.

**Comment by jmatil** [comment]
Issue compreendida
