### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Consulta utilizando o campo "Inscrição"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#134]
Favor verificar a validação da ação de consulta utilizando parâmetros no campo "Inscrição"

![issue19](https://cloud.githubusercontent.com/assets/6584772/6265418/3733cb02-b815-11e4-805d-e492f1ff8eae.png)

**Comment by saires** [comment]
Corrigido, verificar correção.

**Comment by saires** [comment]
Verificar.

**Comment by jmatil** [comment]
Item verificado

![corrigido](https://cloud.githubusercontent.com/assets/6584772/6278174/e2f03b0e-b87b-11e4-9a34-e8e03a0198b1.PNG)
