### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Consulta utilizando o campo "Situação"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#135]
Validar a consulta referente ao fluxo utilizando o campo Situação, pois não está retornando o resultado esperado.

![issue20](https://cloud.githubusercontent.com/assets/6584772/6265527/ae02b1b6-b816-11e4-9802-497bdfab03d8.png)

**Comment by saires** [comment]
Realizar novo teste.

**Comment by jmatil** [comment]
Ao selecionar uma situação que não pertence a nenhum eleitor o sistema não retorna mensagem de alerta.
![issue48](https://cloud.githubusercontent.com/assets/6584772/6411823/6779b5be-be5b-11e4-80e6-9e72f902d286.png)

**Comment by saires** [comment]
Testar novamente.

**Comment by jmatil** [comment]
Problema persiste

**Comment by saires** [comment]
validar.

**Comment by jmatil** [comment]
Issue validada
