### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Apresentação dos itens conforme exigência da documentação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#137]
Verificar o modo de apresentação dos itens e possibilidade de edição dos campos conforme exigência da documentação.

![issue23](https://cloud.githubusercontent.com/assets/6584772/6265821/941f5dc8-b819-11e4-8a00-5f7697499f26.png)

**Comment by saires** [comment]
Esse tratamento deve ser realizado por um web designer. Acredito que o TSE não questione.

**Comment by monicaleite** [comment]
Jailson,

Como a tela contém todos os itens previstos no caso de uso e no intuito de melhorar a visualização da informação, sugiro que a tela fique conforme foi desenvolvida, visto que o protótipo na forma de layout é apenas uma orientação para o desenvolvimento, salvo os casos em que o usuário informe que deseja que seja exatamente igual, o que não é o caso.

**Comment by jmatil** [comment]
Conforme orientação acima a issue será encerrada.
