### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Quantidade de caracteres - Complemento

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#138]
Verificar a quantidade de caracteres exigidos para o campo "Complemento"

![issue24](https://cloud.githubusercontent.com/assets/6584772/6265947/97f6d952-b81a-11e4-8a07-7252c6ba398b.png)

**Comment by saires** [comment]
Ok, verificar correção.

**Comment by jmatil** [comment]
Confirmada a correção
