### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Apresentação dos itens conforme exigência da documentação: Hora/Minuto?

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#139]
Verificar se o item Hora/Minuto deverá ser apresentado.
Obs.: Favor verificar o formato: dia/mês/ano

![issue25](https://cloud.githubusercontent.com/assets/6584772/6266026/a200f90e-b81b-11e4-854b-7a148824726b.png)

**Comment by saires** [comment]
Ok, verificar correção.

**Comment by jmatil** [comment]
Favor confirmar novamente, pois o erro está persistindo

![issue30](https://cloud.githubusercontent.com/assets/6584772/6285662/77cef9cc-b8e5-11e4-8be5-727d456aefc3.png)

**Comment by jmatil** [comment]
confirmado a correção
![corrigido](https://cloud.githubusercontent.com/assets/6584772/6354047/c6b0d918-bc2b-11e4-8b0e-7762a3602004.png)
