### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Itens não implementados

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#140]
Itens não estão implementados

![issue26](https://cloud.githubusercontent.com/assets/6584772/6266144/055b3892-b81d-11e4-829b-8250c2f59fae.png)

**Comment by saires** [comment]
Corrigido, verificar correção.

**Comment by jmatil** [comment]
Confirmado a Implementação

![corrigido](https://cloud.githubusercontent.com/assets/6584772/6277958/1d37cd1a-b87a-11e4-8ea9-7de6ad91a365.PNG)
