### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Interrupção do fluxo

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#141]
Ao acionar o link o sistema direciona para a página do odin

![issue27](https://cloud.githubusercontent.com/assets/6584772/6270043/4783851e-b83e-11e4-90ab-89a6f9ea6794.png)

**Comment by saires** [comment]
Favor realizar novo teste.

**Comment by jmatil** [comment]
Confirmado a correção
