### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Exclusão de Evento

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#142]
Verificar a opção de Exclusão de eventos cadastrados, pois não está sendo possível simular a ação e nem emite a mensagem de impossibilidade.

![issue28](https://cloud.githubusercontent.com/assets/6584772/6284994/fc477010-b8dd-11e4-9723-3c0bea6f93e4.png)

**Comment by saires** [comment]
Favor realizar novo teste.

**Comment by jmatil** [comment]
Reteste realizado. Exclusão sendo realizada.
