### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Inclusão do Evento "Dispensa" sem indicar o "Motivo"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#143]
Verificar a possibilidade de inclusão conforme a RN70

![issue29](https://cloud.githubusercontent.com/assets/6584772/6285121/29bb036c-b8df-11e4-9acc-9db8a9e0cf95.png)

**Comment by saires** [comment]
Favor realizar novo teste.

**Comment by jmatil** [comment]
Reteste realizado. Issue persiste

![corrigido](https://cloud.githubusercontent.com/assets/6584772/6354138/52cf01e0-bc2c-11e4-90ea-7f66083df050.png)

**Comment by saires** [comment]
Esse registro estava inconsistente. Realizar novo teste.

**Comment by jmatil** [comment]
Item corrigido

![corrigido](https://cloud.githubusercontent.com/assets/6584772/6400362/0c734696-bdd7-11e4-9acf-4b6b20952531.png)
