### ISSUE TITLE
CDU_SCM_040_Solicitar_e_Autorizar_Eleitor - Solicitar um Eleitor

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#144]
Prezados,

Ao realilizar uma solicitação de uma "Inscrição" Eleitor, a aplicação fica processando . O sistema realiza o fluxo se sair e voltar para a aplicação novamente,

![1](https://cloud.githubusercontent.com/assets/9218077/6286885/9377742a-b8f3-11e4-9e83-82af5433a809.png)

**Comment by halvesl** [comment]
corrigido!

**Comment by kleiberfaria** [comment]
Verificado na aplicação. Item verificado !
