### ISSUE TITLE
CDU_SCM_040_Solicitar_e_Autorizar_Eleitor - Exclusão de um eleitor solicitado

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#145]
Prezados,

Dúvida;

Ao consultar os eleitores solicitados conforme a imagem, é possivel realizar a exclusão dos mesmos mas sempre o primeiro eleitor que é solicitado esse não é possível excluir.

![33](https://cloud.githubusercontent.com/assets/9218077/6287158/5ae82246-b8f6-11e4-85b9-c10918cc877f.png)

**Comment by halvesl** [comment]
Na solicitação de eleitores somente é possível excluir se a situação estiver como "Solicitado".

**Comment by kleiberfaria** [comment]
Item verificado !
