### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Pesquisa utilizando parâmetro seção

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#146]
Verificar a pesquisa de eleitores utilizando o campo seção, pois não foi possível ser realizado a consulta

![issue32](https://cloud.githubusercontent.com/assets/6584772/6288961/046ba88a-b904-11e4-8752-aff46c2f8203.png)

**Comment by saires** [comment]
Favor realizar novo teste.

**Comment by jmatil** [comment]
Correção confirmada

![corrigido](https://cloud.githubusercontent.com/assets/6584772/6353957/235f04e2-bc2b-11e4-96e5-c349bf4eb8e2.png)
