### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Identificação do Tipo de Mesa

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#147]
Verificar a apresentação do tipo de mesa ao acionar o link de inserção de eventos.

![issue33](https://cloud.githubusercontent.com/assets/6584772/6289276/19338be6-b906-11e4-8af4-59fe8ec4eacf.png)

**Comment by saires** [comment]
Favor realizar novo teste.

**Comment by jmatil** [comment]
Favor avaliar novamente

**Comment by saires** [comment]
Realizar novo teste.

**Comment by jmatil** [comment]
Implementação confirmada
![corrigido](https://cloud.githubusercontent.com/assets/6584772/6411634/310236b6-be59-11e4-9f69-be78f1cee72f.png)
