### ISSUE TITLE
CDU_SCM_040_Solicitar_e_Autorizar_Eleitor - FE5 Inscrição Inexistente

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#148]
Ao informar uma incrição pelo o qual a inscrição não existe, o sistema não esta apresentando a mensagem MSG020 [ Não foi encontrado eleitor com a inscrição informada ]

![33](https://cloud.githubusercontent.com/assets/9218077/6289568/301e4aba-b908-11e4-8978-3e0fc09ee6e1.jpg)

**Comment by halvesl** [comment]
corrigido! Aguardar deploy!

**Comment by kleiberfaria** [comment]
Item verificado !
