### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Apresentação dos itens no "Detalhamento do Evento"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#149]
Verificar a regra relacionada ao detalhamento do evento para a mesa "Função Especial" onde os itens Seção e Número não deverão ser apresentados.

![issue34](https://cloud.githubusercontent.com/assets/6584772/6289914/aa49ad78-b90a-11e4-9a73-4c0bd1b50525.png)

**Comment by saires** [comment]
Corrigido. Favor realizar novo teste.

**Comment by jmatil** [comment]
Correção confirmada

![corrigido](https://cloud.githubusercontent.com/assets/6584772/6400262/93a35918-bdd6-11e4-9f41-df9a3051f7a1.png)
