### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_ Desalinhamento dos Campos na tela Detalhar

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#15]
Os labels dos campos UF, Zona Eleitoral, Pleito Eleitoral e Funções Eleitorais não estão alinhados aos seus respectivos conteúdos, ou seja, os labels estão alinhados à esquerda e o conteúdo centralizado.
No caso de uso esses campos estão centralizados.
![errro_desalinhamento dos campos tela detalhar](https://cloud.githubusercontent.com/assets/6304414/2615911/0363a1ec-bc00-11e3-9a6d-dfa46828efc0.jpg)

Vide anexo.

**Comment by jadossantos** [comment]
O padrão (css) do layout do sistema ainda não foi definido. Entramos em contato com o responsável da criação do CSS e estamos aguardando uma resposta. Iremos tratar isso como uma melhoria.

**Comment by marasb** [comment]
Em relação à centralização dos campos na tela, não precisa mais ser feito, visto que o Layout deve seguir o padrão do SPCA e SJUR e nesses sistemas os campos são alinhados à esquerda.
Já conversei com a Vera em relação a essa situação e ela concordou.
Sendo assim o bug será fechado.
