### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Apresentação dos itens para situação "Nomeado"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#150]
Todos estes itens citados na Regra 85 deverão ser apresentados? Pois tem informações repetidas.

![issue35](https://cloud.githubusercontent.com/assets/6584772/6305049/948fb07c-b90f-11e4-8538-73bb0a85097b.png)

**Comment by monicaleite** [comment]
Se repetem para algumas situações.

**Comment by monicaleite** [comment]
Os itens “Falta a Reunião”, “Falta a Treinamento”, que estavam repetidos foram retirados da regra.

**Comment by jmatil** [comment]
Confirmado a correção conforme documentação atualizada e diponibilizada no Git
