### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Inclusão de Eventos "Tela Odin"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#151]
Na tentativa de incluir um 4º Evento para o eleitor o sistema não confirmou a inclusão e ao realizar novamente o login e clicar no número de identificação do eleitor do qual foi feito a tentativa de inclusão o sistema está direcionando para a tela de sistemas do "Odin"

![issue36](https://cloud.githubusercontent.com/assets/6584772/6305385/01215112-b912-11e4-9566-9221cb150dac.png)

**Comment by saires** [comment]
Favor realizar novo teste.

**Comment by jmatil** [comment]
Correção confirmada
