### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Tipo de Mesa para o Evento

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#152]
O tipo de mesa apresentado na tabela destacada na figura abaixo deveria ser a mesma atribuída ao eleitor através da atribuição de funções?  A eleitora "046010500450" foi atribuida utilizando a MRJ, mas ao apresentar o resultado na tabela de Gerenciamento de Eventos, a mesa está como MRV.

![issue37](https://cloud.githubusercontent.com/assets/6584772/6306129/e3786366-b917-11e4-8965-1e2005828949.png)

**Comment by saires** [comment]
Essa situação é a mesma tratada na issue https://github.com/islssa/SCM/issues/132

**Comment by monicaleite** [comment]
Sávio,

Em conversa com o Jailson, não entedemos a relação dessa issue com a #132 , aqui o que está ocorrendo é que uma mesa que era do tipo MRJ quando consultada esta aparecendo com o tipo MRV.

**Comment by saires** [comment]
Enquanto a correção do UC7 para esse tipo de mesa não ocorrer essa exibição está prejudicada.

**Comment by monicaleite** [comment]
Sávio,

Preciso que vc me oriente o que precisa ser corrigido para que esse erro não ocorra mais.

**Comment by monicaleite** [comment]
Vamos aguardar que o cliente identifique o problema e abra bugzilla para correção.

**Comment by kleiberfaria** [comment]
Foi verificado na aplicação a devida correção !
