### ISSUE TITLE
CDU_SCM_040_Solicitar_e_Autorizar_Eleitor - Pesquisar Inscrição

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#153]
Ao realizar a pesquisa de um eleitor com a sua determinada inscrição, o sistema esta páginando e replicando o mesmo eleitor por várias vezes.

![33](https://cloud.githubusercontent.com/assets/9218077/6306756/4c4cda70-b91d-11e4-9a22-a20836db9ae5.jpg)

**Comment by halvesl** [comment]
corrigido!

**Comment by kleiberfaria** [comment]
Item verificado !
