### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Inclusão de Evento duplicados

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#154]
Verificar a duplicidade de eventos após acionar a opção "Salvar"

![issue38](https://cloud.githubusercontent.com/assets/6584772/6354348/93f08382-bc2d-11e4-84ee-6b513aac9b9b.png)

**Comment by saires** [comment]
Corrigido. Favor realizar novo teste.

**Comment by jmatil** [comment]
Correção confirmada
