### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Pesquisa utilizando como parâmetro o 'Local de Votação'

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#155]
Verificar a consulta de eleitores utilizando como parâmetro o local de votação

![issue39](https://cloud.githubusercontent.com/assets/6584772/6354604/4e55bd54-bc2f-11e4-9925-b573bc457e69.png)

**Comment by saires** [comment]
Favor realizar novo teste.

**Comment by jmatil** [comment]
Favor verificar a pesquisa acrescentando o campo "Seção".

![issue42](https://cloud.githubusercontent.com/assets/6584772/6375355/4be6581e-bcf5-11e4-9186-c819889aa7e3.png)

**Comment by saires** [comment]
Realizar novo teste.

**Comment by jmatil** [comment]
O sistema está trazendo resultado de eleitores cadastrados em outras "Mesas" da qual não são pertencentes.

![issue47](https://cloud.githubusercontent.com/assets/6584772/6411590/cc44ede0-be58-11e4-809b-6e08a842f137.png)

**Comment by saires** [comment]
Testar novamente.

**Comment by jmatil** [comment]
correção confirmada
