### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Botão Limpar / Permanencia do Local de Votação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#156]
Ao acionar o botão limpar o campo local de votação permanece preenchido

![issue40](https://cloud.githubusercontent.com/assets/6584772/6354761/6729886e-bc30-11e4-82fd-2e5b0f1f72d3.png)

**Comment by saires** [comment]
Corrigido. Favor realizar novo teste.

**Comment by jmatil** [comment]
Correção confirmada
