### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Regra 66

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#157]
Não foi possível localizar o Local de Votação para a função especial "Administrador de Prédio" chamado no FA 1.6

![issue43](https://cloud.githubusercontent.com/assets/6584772/6392909/16d6b754-bda4-11e4-99bc-1e01fdfde34e.png)

**Comment by saires** [comment]
realizar novo teste.

**Comment by jmatil** [comment]
Não foi possível simular esta apresentação.

**Comment by saires** [comment]
Esse campo não é tratado em documentação.

**Comment by jmatil** [comment]
Mônica
poderia avaliar conforme relato acima?

**Comment by monicaleite** [comment]
Sávio, 

O Jailson acabou de mostrar na regra que precisa do campo, como assim não está em documentação?

**Comment by saires** [comment]
![cap1](https://cloud.githubusercontent.com/assets/10027679/6468296/e8ad58d4-c1b2-11e4-9ccc-51a5ee8fde49.PNG)
![cap2](https://cloud.githubusercontent.com/assets/10027679/6468300/efaaf1be-c1b2-11e4-9039-c3900dc83edc.PNG)

**Comment by saires** [comment]
Como isso será evidenciado?

**Comment by monicaleite** [comment]
Jailson e Sávio,

Em conversa com o Paulo, devido a entrega já ter sido realizada e essa mudança gerar alteração nos scripts de teste que já estão disponíveis para o cliente, iremos aguardar que o cliente identifique o erro e abra o bugzilla para realizamos a correção.
Entretanto saliento que apesar do campo não está descrito na tela existia uma regra em que deixa claro quando esse campo deveria ser apresentado e foi sinalizada pelo teste a regra, conforme abertura da issue.

**Comment by jmatil** [comment]
Relato compreendido.
