### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Salvar Evento

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#158]
Verificar o comportamento do sistema, pois na tentativa de salvar um evento utlizando a capacidade máxima do campo, o sistema não demonstra se realizou a inclusão na base de dados. Segue imagem da simulação.

![issue44](https://cloud.githubusercontent.com/assets/6584772/6395922/3e671082-bdba-11e4-9a24-e345b4c033f0.png)

**Comment by saires** [comment]
Realizar novo teste.

**Comment by jmatil** [comment]
Situação persiste
![corrigido](https://cloud.githubusercontent.com/assets/6584772/6412016/3384481c-be5d-11e4-9964-bb65875daecf.png)

**Comment by saires** [comment]
não consegui simular.

**Comment by jmatil** [comment]
Verificar novamente

![issue50](https://cloud.githubusercontent.com/assets/6584772/6452650/f40c19e2-c115-11e4-93cb-9c5f3ba8e70b.png)

**Comment by jmatil** [comment]
Confirmado a correçao
