### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_ Falta perfil 'TRE' para realizar os testes

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#16]
O usuário disponibilizado para os testes é perfil "Zona Eleitoral", sendo assim não consigo validar a tela de perfil "TRE", que possui outro comportamento, conforme definido no caso de uso.
Como devo proceder para testar o outro perfil.

**Comment by jadossantos** [comment]
A implementação de Autenticação, LOG e Perfil ainda está pendente, por falta de definição.

**Comment by marasb** [comment]
Vera,
Conforme informado pelo Joel a parte de perfil ainda está pendente por falta de definição.
Nesse caso não tenho como testar a tela do perfil TRE, nós vamos entregar assim mesmo sem essa validação?

**Comment by VeraNakamura** [comment]
Mara,
Quanto ao log, neste momento o pessoal da SECAD está definindo a que nível será feita a auditoria, portanto é uma regra que neste momento não deve ter sido implementada, mesmo existindo no uc. Após definição será retirada ou não.
Quanto ao perfil TRE pelo que eu entendo deve ter sido criado este perfil para testes.

**Comment by marasb** [comment]
Joel,

Tem como criar um perfil TRE para teste?

**Comment by jadossantos** [comment]
Estamos configurando o Odin. Anderson nos passou a instrução e após essa configuração iremos liberar uma nova versão.

**Comment by jadossantos** [comment]
Resolvido.
Versão 1.0.1

![scm tela para selecionar perfil](https://cloud.githubusercontent.com/assets/7116054/2647021/fa74732e-bf45-11e3-9264-f89df103f84b.png)

Criamos alguns botões para simular a atribuição do perfil ao usuário logado.

**Comment by marasb** [comment]
Corrigido. Versão 1.0.1
