### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Qtd de Eventos

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#160]
Verificar se há limitação na qtd de eventos a serem lançados, pois não está sendo possível lançar mais de 10 eventos para uma inscrição, mas o sistema emite a mensagem de sucesso.

![issue46](https://cloud.githubusercontent.com/assets/6584772/6398647/cac65464-bdcb-11e4-99ec-3b8d0ec1919a.png)

**Comment by saires** [comment]
Verificar na aba 2.

**Comment by jmatil** [comment]
Confirmado
