### ISSUE TITLE
CDU_SCM_040_Solicitar_e_Autorizar_Eleitor - Campo Data

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#161]
No campo Período de Solicitação da Zona Eleitoral: Para inserir uma data, a aplicação permite colocar datas fora do formato conforme imagem em anexo.

![11](https://cloud.githubusercontent.com/assets/9218077/6404028/94a4c95c-bdf2-11e4-96c7-4e11efe01fa1.jpg)

**Comment by halvesl** [comment]
corrigido em desenv, favor aguardar o proximo merge e deploy em homolog.

**Comment by kleiberfaria** [comment]
Item verificado também em ambiente de homologação.
