### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Pesquisa de eleitor pertencente a outro município

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#162]
Foi realizado a pesquisa utilizando o número de inscrição, mas com o município diferente de onde foi solicitado o eleitor. O sistema trouxe resultado.

![issue49](https://cloud.githubusercontent.com/assets/6584772/6412355/77a3845a-be61-11e4-8303-0c3029e59deb.png)

**Comment by saires** [comment]
realizar novo teste.

**Comment by jmatil** [comment]
Correção confirmada
