### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Ação não contemplada na documentação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#163]
Não foi identificado esse comportamento nas documentações que envolvam esse caso de uso. Favor verificar com o desenvolvedor a necessidade de inclusão de fluxos, regras e mensagens que contemplem esta ação no sistema.
![issue50](https://cloud.githubusercontent.com/assets/6584772/6450795/1974599a-c109-11e4-92dc-8c1f9feffe4b.png)

**Comment by monicaleite** [comment]
Então deverá ser verificado com o desenvolvimento o porque existe um tratamento que não está descrito no caso de uso, caso precise existir é necessário que quem desenvolvem me passe, o motivo para que eu possa atualizar a documentação.

**Comment by jmatil** [comment]
Ação retirada da aplicação
