### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Entendimento do fluxo / Ação não simulada

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#164]
Precisamos de auxílio para entendimento do fluxo FE7. Exclusão de evento não permitido
![issue51](https://cloud.githubusercontent.com/assets/6584772/6449748/be382da6-c101-11e4-9be4-9520b0aff13f.png)

**Comment by monicaleite** [comment]
Não entendi a dúvida, nesse fluxo fala que se o evento for "Nomeação" e tiver um eleitor atribuído não poderá ser excluído.

**Comment by monicaleite** [comment]
Jailson,

Como a documentação foi homologada com essa lógica, devemos deixar assim e aguardar, caso tenha alguma falha, deverá ser apontada pelo gestor do sistema e aberta uma solicitação de mudança para a documentação e aplicação.

**Comment by jmatil** [comment]
Compreendido

**Comment by saires** [comment]
É necessário revisar a regra de exclusão de evento com o gestor. A regra não trata com clareza os tipos de eventos que podem ser excluídos.
