### ISSUE TITLE
CDU_SCM_007_Atribuir Funcao Eleitoral a Mesario - Tempo de realização da pesquisa

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#166]
O tempo de realização da pesquisa para atribuição da função eleitoral está com o tempo demorado. Isso é comum?

![2](https://cloud.githubusercontent.com/assets/6584772/6971475/2670cca2-d953-11e4-8d25-3f2d80f75192.png)

**Comment by halvesl** [comment]
Corrigido. Favor aguardar próximo deploy.

**Comment by saires** [comment]
Gentileza validar.

**Comment by kleiberfaria** [comment]
Permanece ainda o devido erro relatado.

**Comment by saires** [comment]
Kleiber, isso ocorre com que frequência em 10 tentativas por exemplo? Podemos ver com o leandro a criação de índices para melhorar.

**Comment by jmatil** [comment]
Esta ação está ocorrendo ao primeiro acesso do dia. Retestes serão feitos, caso ocorra com frequência a ação será novamente relatada.
