### ISSUE TITLE
CDU_SCM_040_Solicitar e Autorizar Eleitor - Situação da Solicitação

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#167]
Prezados,

Na tela Autorizar Eleitor de outra Zona Eleitoral, existe um erro na grafia conforme tela em anexo.
![1](https://cloud.githubusercontent.com/assets/9218077/6972666/be586054-d95b-11e4-9be5-28944d0af229.jpg)

**Comment by halvesl** [comment]
Favor, solicitar alteração em banco.

**Comment by jmatil** [comment]
Item corrigido
