### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos - Visualização das Funções após salvar

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#168]
Favor verificar a ação após salvar a configuração da mesa, pois não está como anteriormente quando era possível visualizar a opção "Alterar"

![4](https://cloud.githubusercontent.com/assets/6584772/6972688/dc044c76-d95b-11e4-9976-7bf7afacfad8.png)

**Comment by saires** [comment]
Validar.

**Comment by jmatil** [comment]
Ação validada
![9](https://cloud.githubusercontent.com/assets/6584772/7065352/1df9b32e-de8d-11e4-9bb1-913b2965808e.png)
