### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Convocar Eleitor FA4

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#169]
Ao realizar a pesquisa e o sistema apresentar o resultado, o sistema disponibiliza os eleitores para seleção, mas ao selecionar e acionar a opção (Botão) 'convocar', o sistema direciona para a tela de sistemas do ODIN.

![5](https://cloud.githubusercontent.com/assets/6584772/7046142/25fdb29a-ddda-11e4-9286-f3e434fd93b3.png)

**Comment by saires** [comment]
Validar.

**Comment by jmatil** [comment]
Ação validada
