### ISSUE TITLE
CDU_SPCA_024_Manter_Origem_de_Recurso_Validação da regra de negócio RN3

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#17]
A regra de negócio RN3. Registro de log define:
"O sistema fará o registro de acesso em algumas funcionalidades (incluir, alterar e excluir) do SCM, devendo gravar:
• Matrícula;
• Usuário;
• Informações incluídas, alteradas e/ou excluídas;
• Data da operação;
• Hora da operação;
• IP da máquina.
"
O Registro de Log foi implementado e como devo proceder para validar?

**Comment by jadossantos** [comment]
A implementação de Autenticação, LOG e Perfil ainda está pendente, por falta de definição.

**Comment by marasb** [comment]
Vera,
De acordo com o Joel, a implementação do registro de LOG ainda está pendente por falta de definição.
Sendo assim não temos como testar esse item agora.
A documentação vai continuar fazendo referência ao registro de LOG?

**Comment by VeraNakamura** [comment]
Mara,
Está pendente de definição da SECAD, após definição saberemos se será retirada a regra ou não.
Enviarei um e mail para ver se isso já foi definido.

**Comment by VeraNakamura** [comment]
Mara,
Todas as operações terão log, portanto a RN3 permanece em todos os casos de uso.
