### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuracao de Mesa Receptora de Justificativas - Acesso

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#170]
Na tentativa de alterar uma função disponível e já com eleitor atribuido, o sistema não permite realizar a alteração. Foi preciso acionar a página anterior para ter acesso à aplicação, mas o acesso ao submenu MRV ficou inacessível, pois a aplicação direciona o ator à pagina de sistemas do ODIN

![6](https://cloud.githubusercontent.com/assets/6584772/7050193/f4868ebe-ddf5-11e4-9097-12731d0af9ac.png)

**Comment by saires** [comment]
Validar.

**Comment by jmatil** [comment]
Problema persiste

**Comment by saires** [comment]
Gentileza validar.

**Comment by jmatil** [comment]
Correção confirmada
