### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Incluir Evento à eleitor de outra zona

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#171]
Verificar a possibilidade de inclusão de um evento a um eleitor solicitado e autorizado de outra zona eleitoral e já com função atribuida.

![7](https://cloud.githubusercontent.com/assets/6584772/7051244/423da546-ddfd-11e4-9197-560a13996403.png)

**Comment by saires** [comment]
Os eventos de eleitores solicitados de outra zona devem aparecer na pesquisa de eventos. Gentileza validar correção.

**Comment by jmatil** [comment]
Correção validada
