### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Eleitor Atribuido, função não encontrada

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#172]
O eleitor da zona 21 foi convocado para realizar funções eleitorais na zona 001, mas está sendo permitido realizar consultas para realização de atribuições na zona 21. Essa ação está correta?

![10](https://cloud.githubusercontent.com/assets/6584772/7065737/33f81c20-de91-11e4-8924-eee662af44a6.png)

![12](https://cloud.githubusercontent.com/assets/6584772/7066080/29aaf19e-de95-11e4-9b5d-b19662becbfb.png)

**Comment by saires** [comment]
Os eventos de eleitores solicitados de outra zona devem aparecer na pesquisa de eventos. Gentileza validar correção.

**Comment by jmatil** [comment]
Ação confirmada
