### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Fluxo FA4 pesquisa

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#173]
Verificar a realização da pesquisa utilizando como filtro de pesquisa a situação: Atribuido. O sistema não está filtrando.

![11](https://cloud.githubusercontent.com/assets/6584772/7065920/69144a4e-de93-11e4-92fe-be20e020ed8a.png)

**Comment by saires** [comment]
Jaílson, favor validar correção.

**Comment by saires** [comment]
Gentileza, validar correção.

**Comment by jmatil** [comment]
Correção confirmada
