### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Fluxo FE3

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#175]
Sistema não está emitindo a mensagem solicitada no caso de uso

![13](https://cloud.githubusercontent.com/assets/6584772/7067907/109e196e-dea5-11e4-82b5-acd9c86d9e78.png)

**Comment by saires** [comment]
Validar se a mensagem "Não foi encontrado Eleitor conforme os filtros utilizados para pesquisa." está sendo exibida.

**Comment by jmatil** [comment]
Correção confirmada
