### ISSUE TITLE
CDU_SCM_002_Gerenciar Config de Mesa Receptora - Exclusão

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#176]
Prezados,
Após realizar uma inclusão de Funções Eleitorais, não esta sendo possível realizar a exclusão da mesma.
![1](https://cloud.githubusercontent.com/assets/9218077/7378697/b81609e8-edc5-11e4-8901-25d72147b085.png)

**Comment by saires** [comment]
Gentileza validar a correção.

**Comment by kleiberfaria** [comment]
Item verificado. Obrigado !
