### ISSUE TITLE
CDU_SCM_003_Gerenciar Config de Mesa Recep Justificativa - Exclusão

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#177]
Prezados,

Ao realizar a seleção das Funções Eleitorais, não esta sendo possível realizar a exclusão da mesma conforme tela em anexo. 
![2](https://cloud.githubusercontent.com/assets/9218077/7378889/1e4cc728-edc7-11e4-9fc2-a47625f79d5b.png)

**Comment by saires** [comment]
Gentileza validar a correção.

**Comment by kleiberfaria** [comment]
Item verificado. Obrigado !
