### ISSUE TITLE
CDU_SCM_005_Gerenciar Criterio de Selecao e Base de Eleitores Convocaveis - Acesso

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#178]
O acesso à funcionalidade está impossibilitado de ser realizado.
![1](https://cloud.githubusercontent.com/assets/6584772/7396781/5b725736-ee7a-11e4-9155-4d1d6449d06f.png)

**Comment by saires** [comment]
Gentileza validar a correção.

**Comment by jmatil** [comment]
Correção confirmada.
