### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Acionamento da Pesquisa

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#179]
Ao selecionar o Município "São Mateus" e acionar a opção "PESQUISAR", o sistema direciona o ator à página de sistemas disponíveis na aplicação Odin.

![2](https://cloud.githubusercontent.com/assets/6584772/7397008/d2667a2e-ee7b-11e4-84c7-e63dd135a1b0.png)

**Comment by saires** [comment]
Gentileza validar a correção.

**Comment by jmatil** [comment]
Correção confirmada
