### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_As funções eleitorais não estão ordenadas conforme caso de uso.

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#18]
Foi observado que na tela de inclusão/altearção as funções eleitorais não estão ordenadas conforme o caso de uso e regra de negócio.
Na aplicação está ordenado da seguinte forma:
Selecionadas
1º MESÁRIO
1º SECRETÁRIO
2º MESÁRIO
PRESIDENTE DE MESA

Disponíveis  
2º SECRETÁRIO
SUPLENTE

De acordo com o caso de uso e regra de negócio as funções eleitorais devem ser ordenado da seguinte forma:
Selecionadas
• Presidente de Mesa
• 1º Mesário
• 2º Mesário
• 1º Secretário
Disponíveis
• 2º Secretário
• Suplente

**Comment by jadossantos** [comment]
A lista foi ordenada.

**Comment by marasb** [comment]
Defeito corrigido.
