### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Vínculo

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#180]
Verificar a possibilidade de vinculação de eleitores à função especial. O sistema fica em "loop". Segue imagem da situação.

![3](https://cloud.githubusercontent.com/assets/6584772/7413575/4e738c5e-ef23-11e4-85ce-d7670e11648f.png)

**Comment by saires** [comment]
Desativar as trigger pois um erro está causando esse problema.

**Comment by jmatil** [comment]
O erro foi corrigido, porém não foi informado a solução tomada.  A Issue será fechada, mas retestes serão realizados futuramente, pois não sabemos o que foi feito para a devida solução. (se devido à desativação das triggers ou correções em códigos de desenvolvimento.)
