### ISSUE TITLE
CDU_SCM_002_Gerenciar_Configuração_de_Mesa_Receptora_de_Votos - MSG

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#181]
Prezados,
Conforme tela em anexo, ao realizar uma alteração de configuração da MRV e confirmar, o sistema exibe a [MSG001] Operação realizada com sucesso. Porem na documentação de Regra de Mensagem a messagem é [MSG001] "Configuração realizada com sucesso"

![1](https://cloud.githubusercontent.com/assets/9218077/7414250/d499c010-ef27-11e4-9dbe-7fa7eb2a24c2.jpg)
![1](https://cloud.githubusercontent.com/assets/9218077/7414358/7fb678b2-ef28-11e4-9116-bb286d980c3e.jpg)

**Comment by saires** [comment]
Monica, o Enzo e eu definimos no passado que essa mensagem atual seria mais prática, pois tinha que verificar se era uma inclusão ou alteração. Você poderia mudar a mensagem na documentação nesse caso pela msg002.

**Comment by monicaleite** [comment]
Pessoal, 

Verificando o fluxo de alterar a mensagem que é exibida é a MSG002.

**Comment by jmatil** [comment]
Adaptação confirmada
