### ISSUE TITLE
CDU_SCM_007_Atribuir Função Eleitoral a Mesário - Não atribui

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#182]
Prezados,

Ao Atribuir uma Função Eleitoral Manualmente, o sistema fica em processamento não permitindo a devida atribuição conforme tela em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/7418904/c82f63fa-ef47-11e4-8910-ab41b825ae6f.png)

**Comment by kleiberfaria** [comment]
Lembrando que essa atribuição gera o impacto nos fluxos de exeção dos casos de uso 002 e 003

**Comment by saires** [comment]
Desativar as trigger pois um erro está causando esse problema.

**Comment by jmatil** [comment]
Atribuição sendo realizada com sucesso até o momento
