### ISSUE TITLE
CDU_SCM_038_Consultar Municipio e Local de Votacao - Apresentação de Resultados

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#184]
Ao acessar a funcionalidade através do Menu "Atribuir / Função" o sistema disponibilizou as duas opções de pesquisa: Município e Local de votação. Ao acionar a opção de pesquisa de local de votação sem informar  o município,  a janela referente à pesquisa foi disponibilizada, mas ao informar o local de votação de número:1171. O sistema mostrou apenas o item referente ao município de São Mateus, sendo que para o Município de Jaguaré o mesmo número de local de votação existe, mas não foi apresentado. Segue imagem:

![4](https://cloud.githubusercontent.com/assets/6584772/7420905/ea9d977c-ef56-11e4-8e07-177527dd737f.png)

**Comment by saires** [comment]
Gentileza revisar.

**Comment by jmatil** [comment]
Item revisado. Correção confirmada
