### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Pesquisa sem parâmetros

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#185]
Ao acionar a opção de pesquisa sem que seja informado os parâmetros de pesquisa, o sistema direciona o ator à pagina inicial do sistema ODIN.

![5](https://cloud.githubusercontent.com/assets/6584772/7453347/9cd31644-f23e-11e4-9d74-c08a820f9507.png)

**Comment by saires** [comment]
Gentileza revisar.

**Comment by jmatil** [comment]
Corrigido

![corrigido](https://cloud.githubusercontent.com/assets/6584772/7492838/3edbe01c-f3d2-11e4-93d8-828f22163cb6.png)
