### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Função ou Local de Votação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#186]
Verificar a informação disponibilizada na mensagem do fluxo de exceção 2 - Quantidade informada é inferior à que está gravada. MSG007.
![7](https://cloud.githubusercontent.com/assets/6584772/7492762/c4832b90-f3d1-11e4-8eb0-64b13d3e6570.png)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by jmatil** [comment]
Situação persiste até a data destacada na imagem.
![14](https://cloud.githubusercontent.com/assets/6584772/7565065/21d62f46-f7c3-11e4-9bd2-467038ac0278.png)

**Comment by saires** [comment]
Validar novamente.

**Comment by jmatil** [comment]
correção confirmada
