### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Função especial não existente

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#187]
Ao informar uma função especial não existente e acionar a opção de pesquisa, o sistema direciona o ator à tela inicial do sistema ODIN.

![9](https://cloud.githubusercontent.com/assets/6584772/7515639/01927a36-f49f-11e4-9f70-0849bf75c212.png)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by jmatil** [comment]
Correção confirmada
