### ISSUE TITLE
CDU_SCM_002_Gerenciar_Configuração_de_Mesa_Receptora_de_Votos - Exclusão

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#188]
Prezados,
Ao realizar a exclusão da mesa não esta sendo possivel realizar o fluxo porém é possivel realizar a alteração. 

![1](https://cloud.githubusercontent.com/assets/9218077/7515969/09418008-f4a2-11e4-9704-a5089a8086c6.png)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by kleiberfaria** [comment]
Item verificado, porem não informado a solução tomada pois foi informado pelo DBA que foram desativadas as triggers. Será realizado os testes, para verificar se a desativação impacta para a devida correção.

**Comment by kleiberfaria** [comment]
Foi realizado o teste, porém depois que realiza uma atribuição e ao excluir ainda ocorre o erro não permitindo a exclusão. 

![1](https://cloud.githubusercontent.com/assets/9218077/7565917/41d3badc-f7ca-11e4-9692-8c09583c6bac.png)

![2](https://cloud.githubusercontent.com/assets/9218077/7565919/46e36d92-f7ca-11e4-89e8-09b997f453cd.png)

**Comment by saires** [comment]
Validar novamente.

**Comment by saires** [comment]
Validar para todos os tipos de situação. (Nomeado, Dispensado, etc)

**Comment by kleiberfaria** [comment]
Item verificado !
