### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Fluxo E2

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#189]
Ao informar uma quantidade inferior a que está cadastrada, o sistema emite a mensagem indicando que a função já está preenchida, mas não consta eleitores cadastrados para função especial. Segue imagem de Exemplo.

![10](https://cloud.githubusercontent.com/assets/6584772/7537951/ee8db4c6-f572-11e4-8f48-a4dbdde8449f.png)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by jmatil** [comment]
Correção Confirmada
