### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_ Divergência na documentação em relação ao nome do presidente.

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#19]
Vera,
Existem divergências no nome da função eleitoral Presidente de Mesa nas documentações.
Na tela do caso de uso está descrito a função "Presidente de mesa".
Na descrição dos campos está descrito "Presidente da Mesa Receptora".
Na regra de negócio está descrito Presidente.

Sugiro que o nome da função eleitoral seja padronizado.

**Comment by VeraNakamura** [comment]
Mara,
Os documentos foram corrigidos para Presidente de Mesa Receptora
