### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - campo vazio

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#191]
Ao excluir o valor "0" (zero) diponibilizado no campo e ter acionado a opção "Salvar" o sistema não permitiu acesso à aplicação.

![11](https://cloud.githubusercontent.com/assets/6584772/7542524/d051dad4-f593-11e4-85a2-fec4117c9896.png)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by jmatil** [comment]
A ação persiste até a data/hora marcados na imagem
![15](https://cloud.githubusercontent.com/assets/6584772/7586676/a9d91ed6-f885-11e4-8127-7ddabfe18438.png)

**Comment by saires** [comment]
Validar novamente.

**Comment by jmatil** [comment]
correção confirmada
