### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Pesquisar Função Especial

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#192]
Ao realizar a pesquisa no caso de uso, o sistema direciona o ator à tela inicial do ODIN

![12](https://cloud.githubusercontent.com/assets/6584772/7542605/80e77048-f594-11e4-9990-7cd4af8eb28b.png)

**Comment by saires** [comment]
Voltou ao normal. Erro ocasionado por mudança de nome de coluna de tabela.

**Comment by jmatil** [comment]
Correção confirmada
