### ISSUE TITLE
CDU_SCM_007_Atribuir Função Eleitoral a Mesário - Pesquisar

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#193]
Prezados,

Conforme tela em anexo, não esta sendo possivel realizar a pesquisa na Atribuição Função Eleitoral.
![1](https://cloud.githubusercontent.com/assets/9218077/7542642/e450fb04-f594-11e4-85ac-182e3dad251f.png)

**Comment by saires** [comment]
Voltou ao normal. Erro ocasionado por mudança de nome de coluna de tabela.

**Comment by kleiberfaria** [comment]
Item verificado !
