### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Pesquisar local de votação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#194]
Foi acionado a opção "Limpar" da qual excluiu os resultados que estavam sendo sendo apresentados, mas ao acionar a opção "Pesquisar", o sistema direciona o ator à tela do ODIN.

![13](https://cloud.githubusercontent.com/assets/6584772/7543415/84f25be8-f59a-11e4-81c4-24d4c96232a0.png)

**Comment by saires** [comment]
Ao clicar no botão limpar o mesmo limpará o campo "Quantidade de Eleitores Configurados para um Determinado Local de Votação" da grid.

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Ação compreendida
