### ISSUE TITLE
CDU_SCM_007_Atribuir Função Eleitoral a Mesário - Importar Dados de Outra Eleição

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#195]
Conforme tela em anexo não esta sendo possível importar dados de outra eleição e a funcionalidades abaixo não apresentam as listas sendo que possuo eleitores atribuidos no 1º turno.
- Função Eleitoral Origem:
- Função Eleitoral Destino:

![1](https://cloud.githubusercontent.com/assets/9218077/7571009/07a33d4e-f7eb-11e4-82ba-9ecb9e925522.png)

**Comment by saires** [comment]
Gentileza validar a correção.

**Comment by kleiberfaria** [comment]
Foi realizado o teste e o erro agora ocorre com a aplicação direcionando para tela do ODIN.

![1](https://cloud.githubusercontent.com/assets/9218077/7891451/2a20df3e-0623-11e5-86c9-9a1f9061d4ab.png)

**Comment by saires** [comment]
Validar correção.

**Comment by kleiberfaria** [comment]
Item verificado !
