### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Quantidade não Preenchida

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#196]
Verificar que o sistema está acusando que existe eleitores atribuidos à função especial. Ação não ocorre conforme imagem anexa.

![16](https://cloud.githubusercontent.com/assets/6584772/7587275/6d4df33c-f88b-11e4-8b85-1fc7e411ce4b.png)

**Comment by saires** [comment]
O cálculo foi corrigido. Agora é contado apenas os eleitores com situação diferente de DISPENSADO.

**Comment by jmatil** [comment]
Correção confirmada
