### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Botão Limpar

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#197]
Verificar a funcionalidade da função limpar, pois só está executando a ação para os resultados apresentados e não para os dados preenchidos.

![17](https://cloud.githubusercontent.com/assets/6584772/7587814/5c8f8002-f88f-11e4-988d-28233bfc0ceb.png)

**Comment by saires** [comment]
Ao clicar no botão "limpar" o mesmo deverá limpar o campo "Quantidade de Eleitores Configurados para um Determinado Município" na grid.

**Comment by jmatil** [comment]
Ação compreendida
