### ISSUE TITLE
CDU_SCM_007_Atribuir Função Eleitoral a Mesário - Atribui botão Salvar

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#198]
Ao realizar a funcionalidade "SALVAR", a aplicação está apresentadando a mensagem de [Atribuição realizada com sucesso.] sem ter realizado nenhuma atribuição conforme imagem em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/7592996/40060d84-f8ad-11e4-9cf7-d39406be8af0.png)

**Comment by saires** [comment]
O botão agora permanecerá desabilitado enquanto não for selecionado um eleitor para a função.

**Comment by monicaleite** [comment]
Sávio, 

Favor implementar conforme a documentação, não foi identificado essa regra.

**Comment by saires** [comment]
O erro ocorre devido a implementação seguir a documentação.
Esse botão precisa estar desabilitado ou então será necessário criar um novo fluxo na documentação ou então deixar a aplicação com o bug.

**Comment by saires** [comment]
Poderia criar uma regra de apresentação apenas. "Caso não tenha sido informado nenhum eleitor à função, o botão salvar deverá estar desabilitado". Uma sugestão. Pode melhora-la.

**Comment by monicaleite** [comment]
Para criar regra preciso do gestor para validar e como estamos em fase de entrega não podemos fazer isso.

**Comment by saires** [comment]
Essa melhoria necessita permanecer em código. Remove-la significará mais bugs.

**Comment by monicaleite** [comment]
Jailson,

Foi criada a RAP049 e referenciada no fluxo FA9 passo FA9.7.

**Comment by jmatil** [comment]
Alteração confirmada
