### ISSUE TITLE
FLUXO ALTERNATIVO 1 

### ISSUE THREAD

**Issue by wfalcao** [islssa/SCM#2]
O QUE DIFERE O FLUXO BÁSICO DO FLUXO ALTERNATIVO 1 É APENAS A RN5, JÁ QUE SERÃO ACESSADO PELA MESMA OPÇÃO?

O FLUXO ALTERNATIVO NÃO DEVERIA SER ACESSADO POR OUTRA OPÇÃO DE MENU COMO POR EXEMPLO CONSULTAR MRV E O FLUXO BÁSICO CADASTRAR MRV?
(O SISTEMAS SÓ TERÁ UM MENU?)

FB1
O caso de uso se inicia quando o ator seleciona a opção Gerenciar a Configuração de Mesa Receptora de Votos no menu principal do SCM.
FA1 
Este fluxo se inicia quando o ator seleciona a opção Gerenciar Configuração de Mesa Receptora de Votos no menu principal do SCM [RN5].

VOCÊS INFORMAM QUE OS DADOS REFERENTES A UF E ZONA DEVERÃO SER CARREGADOS DO USUÁRIO LOGADO.
NO MEU ENTENDIMENTO ESSE FLUXO SE TRATA DE UMA TELA DE CONSULTA, ESSES DADOS NÃO DEVERIAM SER OS DADOS ARMAZENADOS NO ATO DA CRIAÇÃO DA MRV?

NESSE FLUXO (FA1) EXISTEM 2 TELAS DE INTERFACE UMA COM TODOS OS CAMPOS COMO SOMENTE LEITURA E OUTRA COM O CAMPO DA ZONA ELEITORAL CARREGADA COM  UMA COMBO BOX CONTENDO AS ZONAS ASSOCIADAS DE UM DETERMINADO TRE.

 ESSA SEGUNDA TELA SERÁ MOSTRADA QUANDO UM USUÁRIO DO TRE CONSULTAR A TELA OU APARECERÁ CASO O USUÁRIO SELECIONE A OPÇÃO DE ALTERAR?

**Comment by danimendonca** [comment]
O Fluxo Básico (FB) é o fluxo de configuração, considerando que ainda não exista nada configurado para aquela MRV.
O Fluxo Alternativo (FA1) é o fluxo de consulta, onde o ator irá consultar as configurações realizadas no fluxo básico. O FA1 apresenta as opções de alterar e excluir que, quando selecionadas pelo ator, irá encaminha-lo para os fluxos FA2 e FA3, respectivamente.

O sistema terá apenas um menu: Configurar MRV
O controle da funcionalidade que será apresentada ao selecionar este menu, será a validação do cadastramento (configuração) da MRV. Caso a mesma ainda não tenha sido configurada, o sistema deverá apresentar a tela do fluxo básico (FB). Caso a MRV já tenha sido configurada, caso o ator acesse o menu Configurar MRV, o sistema deverá apresentar a tela do fluxo alternativo FB2.

No momento do login, o sistema conseguirá identificar a UF e a Zona Eleitoral correspondente ao usuário. O sistema que faz a autenticação dos usuários é o ODIN. O sistema deverá vincular a MRV configurada à Zona e UF do usuário.

A tela 2 (perfil TRE) do FA1 será apresentada quando o TRE acessar o sistema para consultar as configurações de MRV de uma Zona Eleitoral. Neste caso, os botões alterar e excluir devem ser apresentados na tela mas desabilitados pois o perfil TRE poderá apenas consultar.
