### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_ Formatação da tela detalhar

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#20]
Na tela detalhar o sistema está apresentando uma borda ao redor das funções eleitorais selecionadas, porém no caso de uso essa borda não existe.

Também na tela detalhar, as funções eleitorais não estão no mesmo alinhamento da primeira função. No caso de uso a primeira função está na frente do label "Funções Eleitorais Selecionadas" e as demais funções estão abaixo da primeira, porém no mesmo recuo da primeira função eleitoral.

**Comment by jadossantos** [comment]
O padrão (css) do layout do sistema ainda não foi definido. Entramos em contato com o responsável da criação do CSS e estamos aguardando uma resposta. Iremos tratar isso como uma melhoria.

**Comment by marasb** [comment]
Nesse bug o recuo deve ser corrigido para manter o mesmo alinhamento de todas as funções.
A borda deve ser retirada para manter o padrão com os demais sistemas SPCA e SJUR.

![erro_alinhamento e borda tela detalhar](https://cloud.githubusercontent.com/assets/6304414/2644697/195c5006-bf2b-11e3-818f-5b0965d4238b.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 1.0.1

**Comment by marasb** [comment]
Corrigido na versão 1.0.1.
