### ISSUE TITLE
CDU_SCM_007_Atribuir Função Eleitoral a Mesário - Lista de eleitores

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#200]
A Lista de Eleitores Disponíveis só esta sendo apresentada após que realiza a primeira atribuição conforme imagens em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/7593489/082e413e-f8b1-11e4-9897-fc1cdc86c438.png)

![2](https://cloud.githubusercontent.com/assets/9218077/7593496/1054e0fc-f8b1-11e4-89a6-6a8d01c94de6.png)

**Comment by saires** [comment]
Veja se você consegue simular esse problema novamente, uma vez que foi feita uma alteração para que o botão seja apresentado desabilitado caso nenhum eleitor tenha sido selecionado para uma determinada função.

**Comment by kleiberfaria** [comment]
Sávio, ainda o problema ocorre o erro na lista de eleitores. Vão aparecendo os eleitores na medida em que vou atribuindo para as funções eleitorais.

**Comment by saires** [comment]
Kleiber, peço que tente simular novamente o erro e me informar para que possar avaliar o log.

**Comment by jmatil** [comment]
Correção confirmada
