### ISSUE TITLE
CDU_SCM_007_Atribuir Funcao Eleitoral a Mesario - Atribuição à MRJ

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#201]
Ao atribuir um eleitor à alguma função da MRJ e acionar o botão Salvar. O sistema direciona o ator à tela de MRV com as funções não cadastradas, mas na mesma seção.

![2](https://cloud.githubusercontent.com/assets/6584772/7595301/9c4f79d6-f8bc-11e4-878c-ff06ef68c14b.png)

![3](https://cloud.githubusercontent.com/assets/6584772/7595340/c33c715c-f8bc-11e4-9072-fc3688b58d19.png)

**Comment by saires** [comment]
Validar essa correção. Solicitar ao Leandro a carga na tabela Mrj e seguida um numero de mrj para ser utilizado pela zona/pleito logada.

**Comment by jmatil** [comment]
Segundo relatado pelo Leandro a tabela MRJ é do AdmCad.

**Comment by saires** [comment]
Realizar a validação com as MRJ's:
JAGUARÉ    9
JAGUARÉ    789
SÃO MATEUS 8
SÃO MATEUS 987

**Comment by jmatil** [comment]
Correção confirmada
