### ISSUE TITLE
CDU_SCM_003_Gerenciar_Configuração_de_Mesa_Receptora_de_Just - Exclusão

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#202]
Não esta sendo possivel realizar a exclusão MRJ conforme imagem em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/7597319/091f31bc-f8c9-11e4-825c-69d7fb9ebc1e.png)

**Comment by saires** [comment]
Foi realizada uma alteração para que o número da Mrj seja informado durante a atribuição (uc07). Antes estava sendo erroneamente informando a seção, para o caso de Mrj. O Leandro estará criando Mrj's para a zona/pleito do usuário logado e te passando um número de pesquisa válido. A partir daí gentileza testar esse bug novamente, atribuindo eleitores a uma Mrj. Fico no aguardo para corrigir algor.

**Comment by jmatil** [comment]
Correção confirmada
