### ISSUE TITLE
CDU_SCM_002_Gerenciar_Configuração_de_Mesa_Receptora_de_Votos - Alteração da Configuração

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#204]
Na tentativa de realizar a alteração da configuração da mesa receptora de voto, onde constava um eleitor atribuído na função de "Suplente", o sistema emitiu a mensagem indicando que constava um eleitor na situação de Atribuído (Ação correta), mas não permitiu a confirmação da ação solicitada pelo usuário.
Obs: Foi verificado que a situação ocorre justamente quando o eleitor está na função de: Atribuido e Nomeado.

![1](https://cloud.githubusercontent.com/assets/6584772/7609322/3da2032c-f948-11e4-9e2b-007155b2d163.png)

**Comment by saires** [comment]
Validar correção. Observar se caso a exclusão tenha sido realizado com sucesso e mesmo assim a função permanecer na caixa de "Selecionadas" isso quer dizer que existem eleitores com a situação "Dispensado" para a função. Essa permanência é para manter o vinculo das informações no banco de dados.

**Comment by jmatil** [comment]
Favor reavaliar a situação, pois a ação ainda permanece. 
Obs: O mesmo ocorre com a MESA RECEPTORA DE JUSTIFICATIVA

**Comment by saires** [comment]
Gentileza validar. Não tinha subido o deploy.

**Comment by jmatil** [comment]
Verificar a situação relatada na imagem abaixo

![1](https://cloud.githubusercontent.com/assets/6584772/7725598/87678038-fed2-11e4-9cc7-428ffc14ad82.png)

**Comment by saires** [comment]
Isso quer dizer que existem eleitores com a situação "Dispensado" para a função. Essa permanência é para manter o vinculo das informações no banco de dados. Esse requisito deverá ser evoluído no futuro.

**Comment by jmatil** [comment]
Compreendido
