### ISSUE TITLE
CDU_SCM_007_Atribuir Funcao Eleitoral a Mesario - Execução do CDU utilizando a MRJ

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#205]
Ao acionar a opção "Pesquisar",  o sistema não está permitindo a configuração quando o ator utiliza a MESA - MRJ 

![1](https://cloud.githubusercontent.com/assets/6584772/7610318/3f4e50a4-f952-11e4-8dfe-fd0b80d5f806.png)

**Comment by saires** [comment]
Realizar validação com as MRJ's:
JAGUARÉ    9
JAGUARÉ    789
SÃO MATEUS 8
SÃO MATEUS 987

**Comment by jmatil** [comment]
Haverá alguma exceção caso haja incompatibilidade entre Município, Local de Votação e Número. Ou caso o número informado não existir para o tipo de mesa (MRJ) escolhido pelo ator?

**Comment by monicaleite** [comment]
No documento não está previsto isso, nesse caso preciso que me passe como o sistema está se comportando para vermos a melhor forma de adequar a documentação ou a aplicação, dependendo do caso.

**Comment by monicaleite** [comment]
Sávio, 

O que precisa ser feito na documentação, como vc está alterando precisamos da orientação quanto ao comportamento esperado e mudanças na documentação.

**Comment by saires** [comment]
Inserir esse novo fluxo de exceção:
![image](https://cloud.githubusercontent.com/assets/10027679/7939553/05b40c14-0922-11e5-8df2-e5635b2f31fb.png)

sendo chamado no fluxo básico:
![image](https://cloud.githubusercontent.com/assets/10027679/7939656/6711372a-0922-11e5-8fcd-b4c567434c92.png)

**Comment by saires** [comment]
Inserir novo fluxo de exceção: (corrigir numeração)
![image](https://cloud.githubusercontent.com/assets/10027679/7939759/0b99cafa-0923-11e5-8b49-88c21a385196.png)

Sendo chamado a partir do fluxo básico:
![image](https://cloud.githubusercontent.com/assets/10027679/7939741/f89f3b2e-0922-11e5-9c01-9facdcfd580f.png)

**Comment by monicaleite** [comment]
Realizada a inclusão do fluxo de exceção no documento.

**Comment by jmatil** [comment]
Ação confirmada
