### ISSUE TITLE
CDU_SCM_002_Gerenciar_Configuração_de_Mesa_Receptora_de_Votos - Alterar 

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#206]
Conforme imagem em anexo, ao realizar uma "ALTERAÇÃO" de uma configuração da mesa e ao incluir uma função que não tenha eleitor atribuido, ocorre a mensagem de "EXCLUSÃO"

![1](https://cloud.githubusercontent.com/assets/9218077/7632275/a8e3ad14-fa21-11e4-86b0-299dd31ab792.png)

**Comment by kleiberfaria** [comment]
A mesma situação ocorre para a MRJ conforme tela em anexo.
![1](https://cloud.githubusercontent.com/assets/9218077/7637057/968e7fb6-fa41-11e4-836d-0955588d2e4b.png)

**Comment by saires** [comment]
Gentileza tentar simular o erro novamente.

**Comment by jmatil** [comment]
Foi constatado que para a MRV - Mesa Receptora de Votos,  ação foi corrigida, mas para a MRJ - Mesa Receptora de Justificativas, a ação ainda permanece.

**Comment by saires** [comment]
Gentileza validar a correção.

**Comment by jmatil** [comment]
Correção confirmada
