### ISSUE TITLE
CDU_SCM_007_Atribuir Funcao Eleitoral a Mesario - Mesa M.R.J

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#207]
Verificar a quantidade de funções disponibilizadas para realização de atribuições à mesa MRJ.
Funções repetidas.

![1](https://cloud.githubusercontent.com/assets/6584772/7636912/9c05fd3a-fa40-11e4-9357-db39a893961e.png)

**Comment by kleiberfaria** [comment]
Está permitindo realizar a atribuição em duplicidade conforme tela em anexo.
![1](https://cloud.githubusercontent.com/assets/9218077/7636962/f56cc66a-fa40-11e4-91a0-480aaf8b5332.png)

**Comment by saires** [comment]
Gentileza tentar simular o erro novamente e me chamar após o mesmo.

**Comment by jmatil** [comment]
![1](https://cloud.githubusercontent.com/assets/6584772/7724979/bf96ebca-fecc-11e4-9c2f-30092edce5c8.png)

**Comment by saires** [comment]
Foi feita uma limpeza na base. Verificar se esse problema volta a ocorrer, se possível simular os mesmos passos que originou esse problema, para verificarmos se era apenas lixo ou algum erro na aplicação.

**Comment by jmatil** [comment]
Situação persiste

![1](https://cloud.githubusercontent.com/assets/6584772/7883181/dedf093e-05ea-11e5-9a74-90ac8f47f910.png)

**Comment by saires** [comment]
Validar a correção no ambiente de integração e posteriormente em homologação.

**Comment by jmatil** [comment]
Correção confirmada
