### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Função Especial_AutoComplete

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#208]
Na tela "Gerenciar Configuração de Função Especial" no campo [ Função Especial ] na função auto complete a aplicação conforme exemplo da tela em anexo, apresenta no campo digitado 3 funções porem no resultado da lista é apresenta 4 funções.

![1](https://cloud.githubusercontent.com/assets/9218077/7637894/96073eec-fa47-11e4-81bf-b24e9fd20dc0.png)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by kleiberfaria** [comment]
Item verificado !
