### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Atribuir

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#209]
Conforme tela em anexo, a aplicação não esta premitindo realizar a atribuição.

![1](https://cloud.githubusercontent.com/assets/9218077/7638752/57c52c56-fa4d-11e4-85fe-0102943f8199.png)

**Comment by saires** [comment]
Não consegui simular. Kleiber, gentileza me chamar após simular o erro na sua máquina.

**Comment by kleiberfaria** [comment]
Item verificado. A aplicação realizou a atribuição e a exclusão conforme tela em anexo.
![1](https://cloud.githubusercontent.com/assets/9218077/7725792/1d71f7b0-fed4-11e4-97f0-906d9932b384.png)
