### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_ Erro breadcrumb

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#21]
Ao selecionar a tela Home, o bradcrumb (caminho) está sendo apresentado :Você está em: Login > ???primeiro nivel???.

Deve ser retirado o "???primeiro nivel???." e inserir a palavra Home, porém como já está na página Home, então a palavra não deve possuir link.

**Comment by jadossantos** [comment]
Essa tela não existe no caso de uso e criamos para facilitar a navegação. E ainda não existe a tela de autenticação.

**Comment by marasb** [comment]
Erro fechado, devido a justificativa do Joel.
