### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Label Função Especial

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#210]
Prezado,

Conforme tela em anexo, a label "Função Eleitoral" de acordo com o CDU 039 o nome correto é "Função Especial" 

![1](https://cloud.githubusercontent.com/assets/9218077/7654403/341b8812-faf3-11e4-90a2-d7b24f1bd0cc.png)

![2](https://cloud.githubusercontent.com/assets/9218077/7654411/3cadf280-faf3-11e4-8e0c-b616816e3605.JPG)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by kleiberfaria** [comment]
Item verificado !
