### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Atribuir

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#211]
A aplicação esta realizando a atribuição ao clicar no botão [Adicionar Função] sem ter adiconado nenhum eleitor.

![1](https://cloud.githubusercontent.com/assets/9218077/7726808/e6eda49e-feda-11e4-891e-31dfb2a89f3b.png)

**Comment by saires** [comment]
Gentileza realizar a validação da correção.

**Comment by kleiberfaria** [comment]
Realizado teste porem, foi evidenciado o comportamento conforme imagem em anexo. Acionei o botão "Adicionar Função" sem realizar atribuição de eleitor e a mensagem aparece agora como "Inclusão realizada com sucesso"

![1](https://cloud.githubusercontent.com/assets/9218077/7883225/4c0ae852-05eb-11e5-90e1-a8b3b9e43766.png)

**Comment by saires** [comment]
Erro corregido no ambiente de integração. Não foi possível validar no ambiente de homologação. Validar posteriormente para esse ambiente após homologação.

**Comment by kleiberfaria** [comment]
Item verificado !
