### ISSUE TITLE
CDU_SCM_005_Gerenciar Criterio de Selecao e Base de Eleitores Convocaveis - Selecionar Manualmente

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#212]
Verificar a possibilidade de seleção de eleitores manualmente, pois a aplicação não está permitindo a inclusão conforme imagem anexa:

![1](https://cloud.githubusercontent.com/assets/6584772/7841021/6cbc4ba8-0470-11e5-99a8-1893766e17b8.png)

**Comment by saires** [comment]
Não consegui simular esse erro. Gentileza tentar simular o bug novamente.

**Comment by jmatil** [comment]
Verificar a ação com o número de inscrição do eleitor abaixo: 014406361457

![3](https://cloud.githubusercontent.com/assets/6584772/8082564/93f412e8-0f54-11e5-9029-37cbdb97d919.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Correção Validada
