### ISSUE TITLE
CDU_SCM_002_Gerenciar_Configuração_de_Mesa_Receptora_de_Votos - Inclusão Inicial

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#214]
Verificar a necessidade de emissão da mensagem de confirmação da configuração da mesa ao executar o fluxo básico, pois não está relatada na documentação. Caso houver necessidade, a documentação deverá ser atualizada para adaptar-se ao que está implementado.

![1](https://cloud.githubusercontent.com/assets/6584772/7914158/9e5f30ce-084b-11e5-8b1c-91946fcd11a5.png)

**Comment by saires** [comment]
Essa melhoria não deve entrar em documentação no momento conforme orientação do Rivaldo.

**Comment by monicaleite** [comment]
Sávio, 

A aplicação está com fluxos e mensagens que não existem na documentação, quando chegar na parte da FATES essas divergências não irão passar, causando provavelmente nova devolução, você tem mapeados as alterações que está fazendo em divergência com a documentação? No caso a não ser os impeditivos era para seguirmos a documentação, esse é um dos casos?

**Comment by saires** [comment]
Trata-se de uma solução para contornar um bug na exibição das mensagens ocasionado pelo componente. No entanto, essa alteração seria simples em documentação, talvez não necessite de aprovação do gestor. A estratégia para a documentação do SCM sempre foi arcar com o retrabalho dos impactos em código. Esse infelizmente é mais um caso.

**Comment by monicaleite** [comment]
O Jailson está questionando fluxo de exceção, preciso entender o que tem que ser feito, aí posso dizer se é fácil ou não, até agora não entendi o que precisa ser mudado na documentação para ficar de acordo com a aplicação.

**Comment by saires** [comment]
Inserir o passo: "O sistema apresenta mensagem de confirmação [MSG081]". Deve ficar na posição "FB 1.5". As restantes devem ser reposicionadas.

**Comment by monicaleite** [comment]
Jailson, 

O documento foi alterado conforme orientado pelo Sávio, isso resolve??

**Comment by jmatil** [comment]
Resolve
Irei atualizar os artefatos para que não ocorra impacto na entrega e avaliação da FATES
Obs.: Verificar que a mesma situação ocorre para a MRJ -  CDU 003

**Comment by monicaleite** [comment]
Alterado o CDU 003.

**Comment by jmatil** [comment]
Alteração confirmada
