### ISSUE TITLE
CDU_SCM_002_Gerenciar_Configuração_de_Mesa_Receptora_de_Votos - Mensagem

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#215]
Verificar qual mensagem deverá ser emitida ao confirmar a ação de configuração da Mesa.
Obs: Verificar a regra [RN1.1] citada no passo FB1.3. ("Não foi encontrada na documentação")

![1](https://cloud.githubusercontent.com/assets/6584772/7914245/311168d8-084c-11e5-9f1d-764c93cfb815.png)

**Comment by monicaleite** [comment]
Alterada a documentação para MSG002, conforme o Sávio essa mudança já tinha sido firmada com o analista Enzo, e por isso ele implementou assim, logo eu faço a correção da documentação. No momento o git está indisponível assim que voltar ao normal commitarei o aquivo com a mudança.

**Comment by jmatil** [comment]
Alteração confirmada conforme documentação atualizada e disponibilizada
