### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Campo Obrigatório

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#216]
Verificar a mensagem emitida caso haja campo com obrigatoriedade de preenchimento.
Ação referenciada na issue #191

![1](https://cloud.githubusercontent.com/assets/6584772/7918892/0d687cae-086b-11e5-9f52-976ccc86502a.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Verificar a mesma ação para a funcionalidade "Quantidade por local de votação - Administrador de Prédio"

![1](https://cloud.githubusercontent.com/assets/6584772/7958860/d7a4e9e4-09c9-11e5-9e0f-27a2e5bc2adb.png)

**Comment by saires** [comment]
Validar a correção para a função administrador de prédio.

**Comment by jmatil** [comment]
Correção confirmada
