### ISSUE TITLE
CDU_SCM_037_Consultar Pleito Eleitoral - Consulta do Processo Eleitoral

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#217]
O sistema está limitando o campo "Número de Identificação" à quantidade máxima de 10 caracteres, (ação não especificada na documentação), mas ao disponibilizar essa quantidade máxima com informações que possivelmente não exista, o sistema está emitindo a mensagem conforme imagem abaixo:

![1](https://cloud.githubusercontent.com/assets/6584772/7920750/597c0442-0877-11e5-9aba-9edd6db67a5a.png)

**Comment by saires** [comment]
O tamanho dessa informação no banco de dados é de 8.

**Comment by monicaleite** [comment]
mas a documentação diz que tem que ser 10? O banco não pode ser corrigido para atender a documentação?

**Comment by saires** [comment]
Essa tabela é do CAD. Não podemos altera-la.

**Comment by jmatil** [comment]
Segue tela
![1](https://cloud.githubusercontent.com/assets/6584772/7937408/289d1d8a-0916-11e5-8363-f6a5ddbe0098.png)

**Comment by monicaleite** [comment]
Alterado para o tamanho 8.

**Comment by jmatil** [comment]
Correção confirmada
