### ISSUE TITLE
CDU_SCM_037_Consultar Pleito Eleitoral - Seleção do Pleito e Configuração das Mesas

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#218]
Verificar o comportamento do sistema ao selecionar um dos pleitos disponibilizados e logo após selecionar a opção "Selecione". 
Parece que está validando a opção "Selecione" como se fosse um pleito disponibilizado. 
OBS.: A mesma ação ocorre para os outros perfis. EX.: TRE
![1](https://cloud.githubusercontent.com/assets/6584772/7921365/5ca8e4ec-087b-11e5-96cf-b1e81083315c.png)

**Comment by saires** [comment]
Gentileza validar em ambos os perfis.

**Comment by jmatil** [comment]
Correção confirmada
