### ISSUE TITLE
CDU_SCM_037_Consultar Pleito Eleitoral - Parâmetros para pesquisa

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#219]
Avalie os passos seguintes:
1º) Foi informado primeiramente o processo eleitoral e o sistema realizou o autocomplete do campo.
2º) Foi disponibilizado um número de identificação válido, mas pertencente a outro processo eleitoral;
Resultado: O sistema levou em consideração somente o número de identificação. 
Segue imagem:

![1](https://cloud.githubusercontent.com/assets/6584772/7921769/124aa34c-087e-11e5-83c2-41137a88f760.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Correção confirmada para a ação relatada acima
