### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_ Ajustar cabeçalho

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#22]
Foi observado que o cabeçalho do sistema está divergente do padrão SPCA e SJUR, sendo assim, sugiro que seja alterado para ficar adequado aos demais sistemas do TSE.
![erro_cabealho scm](https://cloud.githubusercontent.com/assets/6304414/2645076/b035d4b8-bf2e-11e3-9301-0a8217ebd4fc.png)
![cabealho - sjur e spca](https://cloud.githubusercontent.com/assets/6304414/2645082/b96496dc-bf2e-11e3-9286-a817418289ea.png)

**Comment by rsantanam** [comment]
Resolvido.
Versão 1.0.1

**Comment by marasb** [comment]
Defeito corrigido na versão 1.0.1.
