### ISSUE TITLE
CDU_SCM_007_Atribuir Funcao Eleitoral a Mesario - Pesquisa

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#220]
Não está sendo possível a realização da pesquisa, pois o sistema não está permitindo trazer resultados

![1](https://cloud.githubusercontent.com/assets/6584772/7935240/ae9fee32-0905-11e5-9d6e-f088345e1e1f.png)

**Comment by saires** [comment]
Aguardar homologação do banco de dados e ajustes de permissões nas tabelas. O ambiente de integração está disponível para realização dos teste. Validar esse problema posteriormente em homologação para garantir a estabilidade do sistema.

**Comment by jmatil** [comment]
Sistema normalizado
