### ISSUE TITLE
CDU_SCM_007_Atribuir Funcao Eleitoral a Mesario - Campo Número - MRJ

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#221]
Utilizando a capacidade Máxima permitida de caracteres para realização da consulta no ambiente de integração o sistema disponibiliza a mensagem destacada na imagem:

![1](https://cloud.githubusercontent.com/assets/6584772/7943845/9f12fe18-093d-11e5-881e-c274b65a48d6.png)

**Comment by saires** [comment]
Os campos foram adequados para respeitar o tamanho utilizado no banco de dados. O caso de uso utiliza o tamanho 10 tanto para o campo Seção. O campo Número não existe na documentação, pois se trata da parte do requisito que foi mal elaborado na época com relação a MRJ.

Mônica,
alterar a valor desse campo no UC07.

**Comment by monicaleite** [comment]
Jailson,

Esse campo foi implementado sem que tenha sido levantando com o cliente como deveria ser mudado na documentação, para termos alguma referência para embasar a alteração.

Criei a RAP010 e referenciei no fluxo básico passo FB1.3.

**Comment by jmatil** [comment]
Adaptação confirmada
