### ISSUE TITLE
CDU_SCM_007_Atribuir Funcao Eleitoral a Mesario - Pesquisa Geral

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#222]
O sistema não está trazendo todos os resultados ao ser acionado a opção de pesquisa sem informar parâmetros para pesquisa. Está vinculado somente ao município de "São Mateus"

![1](https://cloud.githubusercontent.com/assets/6584772/7959081/37c3052a-09cc-11e5-8acc-5a952a785af6.png)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by jmatil** [comment]
Correção confirmada
