### ISSUE TITLE
CDU_SCM_037_Consultar Pleito Eleitoral - Mensagem de Alerta

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#223]
Verificar a mensagem de alerta que está sendo emitida ao fundo da imagem, pois nas primeiras entregas, esta mensagem não estava sendo emitida.

![1](https://cloud.githubusercontent.com/assets/6584772/7962448/d01c0b52-09e3-11e5-83c5-2bf5a399a82f.png)

**Comment by saires** [comment]
Por questões técnicas dos componentes utilizados para a construção do sistema, a mensagem ficará apenas no fundo, não ficando mais na pop-up. Para que a pop-up não fique em cima da mensagem, a mesma foi reposicionada na tela. Essa mudança ocorreu também para as pop-up de pesquisa de município e local de votação.

**Comment by jmatil** [comment]
Adaptação confirmada
