### ISSUE TITLE
CDU_SCM_037_Consultar Pleito Eleitoral  - Perfis

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#224]
Preciso de perfis de acesso para simular os itens conforme exigido na documentação para este e outros casos de uso.

![1](https://cloud.githubusercontent.com/assets/6584772/7966466/9ecb5a50-09fa-11e5-8770-93dc10aa5d59.png)

**Comment by saires** [comment]
Mônica, as funcionalidades Gerenciar funções especiais (UC04) e Gerenciar configuração de mesa receptora de votos (UC02) não utilizam os perfis TSE e CGE. Acho que essa opção de consulta 'C' pode ser removida das colunas TSE e CGE da regra de negócio.

**Comment by jmatil** [comment]
Confirmado a retirada de acesso de alguns perfis para algumas funcionalidades. Estaremos validando as funcionalidades para confirmarmos o que está disponibilizado na documentação atualizada
