### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Gerênciar Configuração de Função Especial

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#225]
Verificar a possibilidade de execução deste caso de uso para o perfil TRE, pois o comportamento está relatado na imagem abaixo:

![1](https://cloud.githubusercontent.com/assets/6584772/7966842/0922b360-09fd-11e5-8178-65a1bedb621a.png)

**Comment by saires** [comment]
A opção de salvar não está mais disponível para o perfil TRE. Os campos não estão mais editáveis.

**Comment by jmatil** [comment]
Confirmado
