### ISSUE TITLE
CDU_SCM_007_Atribuir Funcao Eleitoral a Mesario - Suplente

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#226]
Verificar a situação do sistema, pois está acusando que há um eleitor na situação de suplente, mas não consta essa função cadastrada na mesa. 
É possível visualizar essa atribuição através do caso de uso 41. Mesa MRJ

![1](https://cloud.githubusercontent.com/assets/6584772/7969937/d22bea2a-0a10-11e5-869c-3e0b49b5c57b.png)

**Comment by saires** [comment]
Foi verificado que se tratava de lixo na base. Verificar se algum registro permanecerá nessa situação após os testes.

**Comment by jmatil** [comment]
Situação normalizada até o momento
