### ISSUE TITLE
CDU SCM 003 Gerenciar Configuração de Mesa Receptora de Justificativa - Referência à perfis

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#227]
Não foi encontrado a opção de referência à consulta a configuração da MRJ na regra de negócio. Essa ação deverá ser disponibilizada no sistema para o perfil TRE?
Obs.: 
1) RN81. Matriz Perfil X Funcionalidade;
2) É citado no caso de uso a utilização do perfil TRE.

![1](https://cloud.githubusercontent.com/assets/6584772/8006813/702262e2-0b6d-11e5-8b8a-cf0fcc48da4d.png)

**Comment by saires** [comment]
A regra 81 foi alterada. Foi inserida a funcionalidade "Gerenciar Configuração de Mesa Receptora de Justificativas” para os perfis Zona e TRE. Disponível na versão 1.67 das Regras de Negócio.

**Comment by jmatil** [comment]
Inclusão confirmada
