### ISSUE TITLE
CDU_SCM_007_Atribuir Funcao Eleitoral a Mesario - Pesquisa pelo Número

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#228]
Ao realizar a pesquisa com um parâmetro específico para a MRJ, o sistema não trouxe resultado favorável sendo que existe este número para o município de JAGUARÉ.

![1](https://cloud.githubusercontent.com/assets/6584772/8010941/0cc1a208-0b8b-11e5-9d87-c6573cf67836.png)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by jmatil** [comment]
Ação validada
