### ISSUE TITLE
CDU_SCM_003_Gerenciar_Configuracao_de_Mesa_Receptora_de_Justificativas - Nomenclatura do Menu

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#23]
<b>Inconsistência:</b> Divergências nos nomes dos menus do CDU e da aplicação.
<b>Proposta:</b> Negociar a possibilidade de redução dos nomes dos menus.

**Comment by VeraNakamura** [comment]
Segue a sugestão de nomes das funcionalidades que serão apresentadas no Menu.
• Gerenciar Configuração de Mesa Receptora de Votos;  
                 Configurar MRV

• Gerenciar Configuração de Mesa Receptora de Justificativas;
                 Configurar MRJ

• Gerenciar Configuração de Função Especial; 
                Configurar Função Especial

• Gerenciar Critério de Seleção e Base de Eleitores Convocáveis; 
                Selecionar por Critério

• Atribuir Função Eleitoral a Mesário; 
                Atribuir Função 

• Atribuir Função Especial ao Eleitor; 
               Atribuir Função Especial

• Consultar Pleito Eleitoral ; 
               Consultar Pleito

• Gerenciar Evento; (Este não precisa ser redefinido nome pequeno);

• Consultar Município e Local de Votação; (Este não precisa ser redefinido, pois não será   chamado pelo menu);

• Solicitar e Autorizar Eleitor; 
              Autorização de eleitor

**Comment by imotac** [comment]
Vera,
Como o menu adotado no layout do SCM é horizontal, seria interessante que agrupasse os item de menu, pois não há espaço suficiente para aloca-los.
Segue abaixo uma sugestão de agrupamento:
- Atribuir
  - Função
  - Função Especial
- Autorização de eleitor
- Configurar
  - Critério
  - Evento
  - Função Especial
  - MRJ
  - MRV
- Consultar
  - Pleito

**Comment by VeraNakamura** [comment]
Ok.

**Comment by jadossantos** [comment]
Ok.
