### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuração de Mesa MRV e MRJ - [Salvar "sem" funções pré-selecionadas]]

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#230]
Prezados,

Ao realizar o fluxo acionando o botão [Salvar] e sem ter realizado as funções eleitorais pré-selecionadas, a aplicação apresenta a mensagem [Operação realizada com sucesso.] porem ser ter realizado uma inclusão de configuração de MRV apenas acionando o botão "Salvar" conforme telas em anexos. Lembrando que vale também para MRJ.

![1](https://cloud.githubusercontent.com/assets/9218077/8012254/5a5e1dce-0b96-11e5-92e8-a279d6965cb6.png)
![1 1](https://cloud.githubusercontent.com/assets/9218077/8012256/5de03cfc-0b96-11e5-9905-e55d5df0c0f6.png)

**Comment by saires** [comment]
Validar correção.

**Comment by kleiberfaria** [comment]
A aplicação esta direcionando para o ODIN.

**Comment by saires** [comment]
Esse problema foi ocasionado após a exclusão do evento ATRIBUIDO, que acabou deixando registro órfão na base. A funcionalidade de exclusão foi corrigida e esse problema não deve ocorrer mais.

**Comment by kleiberfaria** [comment]
Item verificado. A funcionalidade está ok. O script de teste foi finalizado para essa funcionalidade.
