### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Eleitores Atribuídos

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#231]
O sistema não está retornando o resultado com todos os eleitores com a situação "Atribuído" para a configuração de mesa tipo MRJ

ELEITORES ATRIBUÍDOS
![1](https://cloud.githubusercontent.com/assets/6584772/8012463/20006af4-0b98-11e5-9a95-222661cbb068.png)

PESQUISA NO CASO DE USO UTILIZANDO A MESA - MRJ
![1](https://cloud.githubusercontent.com/assets/6584772/8012486/5aced5b2-0b98-11e5-9402-b81e9e2ba45e.png)

**Comment by saires** [comment]
Foi verificado que se tratava de lixo na base. Verificar se algum registro permanecerá nessa situação após os testes.

**Comment by jmatil** [comment]
correção confirmada
