### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuração de MRV - Excluir Config MRV

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#232]
Prezado,

Ao realizar um exclusão de uma Configuração de Mesa Receptora de Votos e voltar para o menu principal CONFIGURAR >> MRV  a aplicação permanece com a configuração sem deixar que realize a exclusão. Lembrando que vale também para MRJ. 

![3](https://cloud.githubusercontent.com/assets/9218077/8057026/1d2d9588-0e84-11e5-893a-1e3124b24c64.png)

**Comment by saires** [comment]
Nesse caso, uma eleitor está dispensado para o pleito "1º Turno" da zona 21. Esse fluxo não está levando em consideração a exclusão do evento (RN67). A exclusão não foi realizada, mas uma mensagem de sucesso foi apresentada. No lugar deveria ser uma mensagem informando essa situação ao usuário.

Isso deve ser tratado como uma melhoria.

![image](https://cloud.githubusercontent.com/assets/10027679/8058877/e1dfe60c-0e92-11e5-948e-afc9104ca9a3.png)

**Comment by kleiberfaria** [comment]
No aguardo para a exclusão dos eleitores "dispensados" para a execução do script de teste.

**Comment by saires** [comment]
Kleiber, vamos seguir a regra deixando a aplicação excluir eventos do tipo "Dispensado". Esse evento só não será excluído se o Edital for gerado. Neste momento não temos como trabalhar com essa informação afirmativa, pois a mesma será tratada em iterações futuras. Portanto, qualquer eleitor, independentemente da sua situação será excluído, assim como todos os seus eventos.

**Comment by kleiberfaria** [comment]
Item verificado Sávio ! Exclusão esta sendo realizada.
