### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial  - Valores Possíveis

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#233]
Verificar os valores possíveis para o campo destacado na imagem. Para a inclusão o sistema deverá exigir números maiores ou igual a 999 e para alteração valores menores que 9999.

![1](https://cloud.githubusercontent.com/assets/6584772/8057349/f6c0c52a-0e86-11e5-910c-5cc5fd905f89.png)

**Comment by saires** [comment]
Documentação alterada. Gentileza validar as alterações.

**Comment by jmatil** [comment]
Alteração confirmada
