### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Limpar/Pesquisar

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#234]
Ao Consultar a configuração de função especial por Município (PERFIL TRE) [FA6] utilizando o filtro ADMINISTRADOR DE PRÉDIO, o sistema apresentou o resultado (Ação correta), mas ao acionar o botão "Limpar" o sistema executou a pesquisa geral de funções especiais.

![1](https://cloud.githubusercontent.com/assets/6584772/8058659/4fd331d4-0e91-11e5-97b2-90556ad5ba23.png)

**Comment by saires** [comment]
Validar a ação do botão limpar. Agora, ele limpa o campo "Função Especial" para o perfil TRE.

**Comment by jmatil** [comment]
Item validado
