### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Campo Editável ou não?

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#235]
Confirmar se a ação de edição destes itens são permitidos, pois há incompatibilidade entre documento e sistema. 
Obs: Perfil= TRE

![1](https://cloud.githubusercontent.com/assets/6584772/8058771/301b5f46-0e92-11e5-9ac2-1fd71de68d1a.png)

**Comment by saires** [comment]
Documentação alterada. Gentileza validar.

**Comment by jmatil** [comment]
Alteração confirmada
