### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial  - Opção "Limpar"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#236]
Não foi possível realizar a ação de Limpeza de campos conforme relatado na documentação utilizando o perfil TRE

![1](https://cloud.githubusercontent.com/assets/6584772/8058898/ff6bd2f8-0e92-11e5-9f31-e0f74f33341f.png)

**Comment by saires** [comment]
A documentação foi corrigida com a ação para o perfil TRE. Verificar a versão 1.8 do UC04.

**Comment by jmatil** [comment]
Verifica a correção e adaptação.
