### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial  - Entendimento

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#237]
Há possibilidade de execução deste fluxo destacado na imagem para o fluxo alternativo 7 ?

![1](https://cloud.githubusercontent.com/assets/6584772/8059295/883fb17e-0e95-11e5-90b2-8fb20a49441e.png)

**Comment by saires** [comment]
Correção disponível a partir da versão 1.7 do caso de uso. Esses fluxo não são necessários no FA6 e no FA7.

**Comment by jmatil** [comment]
Atualização confirmada
