### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial  - Mensagem de Alerta

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#238]
Haverá alguma tratamento ou mensagem de alerta ao usuário caso seja informado uma zona eleitoral incompatível com o município, ou permanecerá a que está na aplicação? "No records found."

![1](https://cloud.githubusercontent.com/assets/6584772/8059822/57d51076-0e98-11e5-84d6-041116c3c236.png)

**Comment by saires** [comment]
A documentação foi alterada. Uma nova regra foi estabelecida para essa caixa de seleção. Gentileza observar a versão 1.8 do UC04.

**Comment by jmatil** [comment]
Confirmado a atualização
