### ISSUE TITLE
SCM_CDU_003_Gerenciar Configuracao de Mesa Receptora de Justificativas - Voltar

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#239]
O botão está habilitado, mas não está executando nenhuma função para o perfil TRE

![1](https://cloud.githubusercontent.com/assets/6584772/8060401/69f42708-0e9b-11e5-97f9-7b04b279b0fd.png)

**Comment by saires** [comment]
O botão voltar não será mais exibido nesse ponto. Ele será exibido após a seleção da opção Alterar, apenas para o perfil Zona Eleitoral.
A documentação foi corrigida quanto a isso. Observar a versão 1.10 do UC03.

**Comment by jmatil** [comment]
Atualização confirmada
