### ISSUE TITLE
CDU_SCM_003_Gerenciar_Configuracao_de_Mesa_Receptora_de_Justificativas - Implementação do log

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#24]
<b>Inconsistência:</b> Falta da implementação do log, conforme previsto no FB 1.4.
<b>Proposta:</b> Definir junto ao cliente, a estratégia de implementação do log.

**Comment by VeraNakamura** [comment]
Este item já foi definido.

**Comment by jadossantos** [comment]
Ok.
