### ISSUE TITLE
SCM_CDU_002_Gerenciar Configuracao de Mesa Receptora de Votos - Voltar

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#240]
O botão voltar não esta ativo. Verificar a funcionalidade do mesmo. Lembrando que ocorre também para o SCM_CDU_003_Gerenciar Configuracao de Mesa Receptora de Justificativas - Voltar.

![3](https://cloud.githubusercontent.com/assets/9218077/8063921/e10aa8aa-0ead-11e5-8a28-082fbe904291.png)

**Comment by saires** [comment]
O botão voltar não será mais exibido nesse ponto. Ele será exibido após a seleção da opção Alterar.
A documentação foi corrigida quanto a isso. Observar a versão 1.10 do UC03.

**Comment by kleiberfaria** [comment]
Item verificado !
