### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Local de Votação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#241]
Verificar se o local de votação deverá permanecer ou não na aplicação, pois não está sendo citado na documentação.
Fluxo: FB1.5

![1](https://cloud.githubusercontent.com/assets/6584772/8065347/4f61525a-0eb7-11e5-8622-72c8c88866a0.png)

**Comment by saires** [comment]
Validar correção. A coluna Local de Votação só deve ser exibida caso a função especial seja "Administrador de Prédio".

**Comment by jmatil** [comment]
Adaptação confirmada
