### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Apresentação dos Itens

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#242]
O sistema deverá apresentar os itens (Inscrição e Pesquisar) após o ator selecionar (clicar) o item correspondente ou após realização da pesquisa.
Avaliar os passos: FB1.5 & FB1.6

![1](https://cloud.githubusercontent.com/assets/6584772/8065654/28ad85dc-0eb9-11e5-9021-e5373ce08e75.png)

**Comment by saires** [comment]
Validar correção. O campo e o botão só deverão aparecer após clicar no link com a funcionalidade ou o link de local de votação, caso a função seja Administrador de Prédio.

**Comment by jmatil** [comment]
Ação confirmada
