### ISSUE TITLE
SCM_CDU_002_Gerenciar Configuracao de Mesa Receptora de Votos - ODIN

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#243]
Ao clicar no botão MRV no menu do SCM a aplicação é direcionada para o ODIN. 

![3](https://cloud.githubusercontent.com/assets/9218077/8081635/d1c6575a-0f4c-11e5-95ff-9f6d3830f4de.png)

**Comment by jmatil** [comment]
Ação impedi a execução inicial do CDU 041 - Gerenciar Eventos

**Comment by saires** [comment]
Erro ocasionado pela exclusão dos eventos através do UC41, que deixou um registro órfão, sem eventos para o eleitor. O mesmo foi corrigido para que esse problema não volte a ocorrer.

**Comment by kleiberfaria** [comment]
Item verificado Sávio. Não esta mais ocorrendo o erro.
