### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Atribuição

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#244]
Verificar o impedimento para atribuir função especial a eleitor solicitado e autorizado pertencente a outra zona eleitoral. 

![3](https://cloud.githubusercontent.com/assets/6584772/8082804/6c537ca4-0f56-11e5-8107-5f79589f0731.png)

**Comment by saires** [comment]
Validar correção do bug. Os fluxo de Não autorizado, Autorizado e Aguardando Autorização foram corrigidos para o UC39.

**Comment by jmatil** [comment]
Correção confirmada
