### ISSUE TITLE
CDU SCM 003 Gerenciar Configuração de Mesa Receptora de Justificativa - Exclusão

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#245]
Verificar se a possibilidade de exclusão da opção "atribuido" no caso de uso 41 - Gerenciar evento, impossibilita a exclusão do registro no caso de uso 003 - Gerenciar configuração de mesa receptora de justificativa.

CDU 041 - GERENCIAR EVENTO
![3](https://cloud.githubusercontent.com/assets/6584772/8082988/d537df48-0f57-11e5-8fd8-1946e8a5fc74.png)

CDU 003 - GERENCIAR CONFIGURAÇÃO DE MRJ
![4](https://cloud.githubusercontent.com/assets/6584772/8083006/f31f6b3e-0f57-11e5-9e10-dec29dbb3d3a.png)

**Comment by saires** [comment]
A exclusão de evento foi corrigida. Ela estava deixando registros órfão e isso estava ocasionando o erro relatado.

**Comment by jmatil** [comment]
Correção confirmada
