### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - importação de dados de outra eleição

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#246]
Verificar a ação de importação de dados de outra eleição, pois o sistema está indicando que não existe eleitores atribuido, sendo que há eleitores atribuidos à funções em eleições anteriores.

![3](https://cloud.githubusercontent.com/assets/6584772/8088928/224c4ab2-0f7b-11e5-81b5-84ee66a46f45.png)

![4](https://cloud.githubusercontent.com/assets/6584772/8088934/2f2bd950-0f7b-11e5-88f3-1908e85eb70c.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Correção confirmada
