### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Resultado Duplicado

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#247]
Ao realizar a pesquisa utilizando o número de inscrição, o sistema está apresentando resultado duplicado

![5](https://cloud.githubusercontent.com/assets/6584772/8089136/570602a6-0f7c-11e5-8a88-4c35ed3a973b.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Correção validada
