### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Mensagem

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#248]
Verificar a mensagem de emissão para um eleitor solicitado, mas que está aguardando autorização da zona de origem
Observação: A ação ocorre para os fluxos FE4 e FE5

![5](https://cloud.githubusercontent.com/assets/6584772/8089679/cd29c28a-0f7f-11e5-91a8-153f1625792a.png)

**Comment by saires** [comment]
Validar correção. A mensagem 23 agora está sendo exibida.

**Comment by jmatil** [comment]
Correção confirmada
