### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Atribuição Automática

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#249]
Verificar a ação de atribuição de eleitores automaticamente 

![6](https://cloud.githubusercontent.com/assets/6584772/8091518/a46b1c9e-0f8a-11e5-83f8-6064ca4f7aa8.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
ação não persiste.
