### ISSUE TITLE
CDU_SCM_003_Gerenciar_Configuracao_de_Mesa_Receptora_de_Justificativas - Problemas nos Fluxos

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#25]
<b>Inconsistência:</b> Nos quadros de definições dos campos (FB1, FA1, FA2, FA3), o campo “Função Eleitoral” está fazendo referência à RN1, enquanto deveria fazer à RN2.
<b>Proposta:</b> Atualizar CDU.

**Comment by VeraNakamura** [comment]
Corrigido.

**Comment by jadossantos** [comment]
Ok.
