### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Exclusão de Eleitores

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#250]
A execução da exclusão dos eleitores atribuídos deverá se de modo automático ou o ator deverá selecionar o eleitor de deseja excluir e logo após acionar a opção 'Salvar'?
![6](https://cloud.githubusercontent.com/assets/6584772/8092078/e72c0e0a-0f8d-11e5-898a-284baf9cb32e.png)

**Comment by saires** [comment]
Esse fluxo foi corrigido. Disponivel no UC39 versão 1.2

![image](https://cloud.githubusercontent.com/assets/10027679/8097591/73a7d61c-0fba-11e5-8c65-13a67f0c3fca.png)

**Comment by jmatil** [comment]
Atualização confirmada
