### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Apresentação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#251]
Verificar a apresentação entre a interface da documentação ou o próprio sistema para os itens destacados na imagem. A apresentação deverá ser por siglas, palavras ou números?

![6](https://cloud.githubusercontent.com/assets/6584772/8092411/ed69c9e0-0f8f-11e5-9a5e-65868100987b.png)

**Comment by saires** [comment]
Campos corrigidos na documentação. versão 1.2

**Comment by jmatil** [comment]
confirmado a atualização
