### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Função Especial / Link

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#252]
Verificar se a documentação ou o sistema está em desacordo com o solicitado, pois a opção "Função Especial" está desativada contrariando a ação relatada na documentação.

![6](https://cloud.githubusercontent.com/assets/6584772/8092552/f39d35e4-0f90-11e5-82f2-2e4794e00b7e.png)

**Comment by saires** [comment]
A documentação foi alterada para esse fluxo 9.Esse link não devera aparecer caso uma função seja de administrador de prédio.

**Comment by jmatil** [comment]
Confirmado a alteração
