### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Opção Salvar

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#253]
Mensagem emitida ao escolher o eleitor, acionar a opção de exclusão sem acionar o botão salvar

![39](https://cloud.githubusercontent.com/assets/6584772/8105952/d608eee6-1013-11e5-9a9a-1819370a8b4e.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
correção validada
