### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Local de Votação / Administrador de Prédio

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#254]
Verificar a Situação
1. Acessar a funcionalidade utilizando como parâmetro o Município "São Mateus"
2. Com quantidade necessária para a função "Administrador de Prédio", acionar o botão "Quantidade por Local de Votação"
Resultado: O sistema está trocando o município para "JAGUARÉ" conforme destacado na imagem.

![39](https://cloud.githubusercontent.com/assets/6584772/8107037/ce4df292-101c-11e5-95e8-160ed088d7c5.png)

![391](https://cloud.githubusercontent.com/assets/6584772/8107106/30a7242c-101d-11e5-8e52-785a459a3b04.png)

**Comment by saires** [comment]
Gentileza verificar correção.

**Comment by jmatil** [comment]
Correção confirmada
