### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Botão Adicionar Função

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#255]
Verificar a ação do botão "adicionar função", pois ao acioná-lo após realização de uma atribuição o sistema emite uma mensagem de "atribuição realizada com sucesso" sendo que não foi acionado o botão "Salvar".

![39](https://cloud.githubusercontent.com/assets/6584772/8109170/b88c55c0-102b-11e5-9e20-5d2b27ab80b4.png)

![391](https://cloud.githubusercontent.com/assets/6584772/8109175/bd6e6ec0-102b-11e5-85c7-0e007b430432.png)

**Comment by saires** [comment]
Essa funcionalidade foi corrigida. Foi criada uma regra para esse botão permanecer desabilitado caso não tenha mais funções para remover. Avaliar versão 1.3 do UC39.

**Comment by jmatil** [comment]
Correção verificada
