### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Remover Função

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#257]
A mensagem de "Exclusão Realizada com Sucesso" está sendo emitida sem que ocorra a ação, ou seja não existe função especial vazia, mas a mensagem está sendo emitida ao ser acioando o botão.

![39](https://cloud.githubusercontent.com/assets/6584772/8113049/f765aca4-1041-11e5-85bb-138213676f9b.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Confirmada a correção
