### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Administrador de Prédio

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#258]
O sistema não está permitindo atribuir eleitores à função Administrador de Prédio sendo que há quantidade necessária de vagas para atribuição.
![39](https://cloud.githubusercontent.com/assets/6584772/8113886/6e250722-1047-11e5-8d8f-7437dc98944d.png)

**Comment by saires** [comment]
Nesse caso a mensagem se refere a quantidade que deve ser definida para o local de votação. Observe que não existe quantidade definida para nenhum local de votação:

![image](https://cloud.githubusercontent.com/assets/10027679/8115267/903f679a-1050-11e5-8b3a-852b60141c23.png)

**Comment by jmatil** [comment]
Confirmado. Item compreendido
