### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Mensagem FE6

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#259]
Verificar a mensagem emitida na simulação do Fluxo de exceção 6
![39](https://cloud.githubusercontent.com/assets/6584772/8114090/884cfe74-1048-11e5-953e-80bfb84aa55c.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Não foi possível verificar se a documentação ou o sistema foi atualizado. Ação permanece

**Comment by saires** [comment]
Utilizar algum desses eleitores pra simular a msg025
JAGUARÉ:
014419921406
015352221465
017369821473
015804311430
015953851481
014421281430
015944281406
012160351406
015353771406
013315181481
015353981422
014424761422
014419981406
017294051430
017363161406
017298541473
017363611465
015947901449
015951351490
016837121465
015351601422
016837491457
015351721465
015947201430
017365001473
022736711490

**Comment by jmatil** [comment]
Foi reavaliado o fluxo e percebido que a exceção não é chamada para esta ação.
