### ISSUE TITLE
CDU_SCM_003_Gerenciar_Configuracao_de_Mesa_Receptora_de_Justificativas - Dependências dos CDUs 007 e 039

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#26]
<b>Inconsistência:</b> Ao alterar/excluir uma MRJ, a rotina não está considerando o status dos eleitores atribuídos à função, devido à falta da codificação dos CDU’s 007 e 039.
<b>Proposta:</b> Após realizar a construção dos CDU’s 007 e 039, ajustar a rotina de alteração e exclusão do CDU 003, para que possam alterar (Conforme a RN04) os status dos eleitores atribuídos.

**Comment by VeraNakamura** [comment]
Joel,
Isso mesmo, o cliente esta ciente que o teste do CDU003 estará 100% após a codificação dos CDU´s 007 e 039.

**Comment by jadossantos** [comment]
Ok.
