### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Remover Função

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#260]
Ao acionar a opção para "Remover Função" o sistema está emitindo a mensagem de impossibilidade de adicionamento de função especial.

![39](https://cloud.githubusercontent.com/assets/6584772/8129506/384e0bd2-10e0-11e5-8132-4286d1575000.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Retificando
A ação ainda permanece conforme imagem anexa
![39](https://cloud.githubusercontent.com/assets/6584772/8188738/078921b6-142e-11e5-8791-bd2ad48aa371.png)

**Comment by saires** [comment]
Erro ocorre ao remover um eleitor da função e depois clicar em remover.

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
correção confirmada
