### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - LABEL

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#261]
Verificar a necessidade de inclusão da LABEL com a função especial selecionada.

![39](https://cloud.githubusercontent.com/assets/6584772/8130924/1e92b956-10ed-11e5-9ee3-c8872cef5249.png)

**Comment by saires** [comment]
Essa tela foi corrigida. Todas as telas de atribuição devem ter no topo "Municipio" e "Quantidade de eleitor atribuído para a função", inclusive para a função Administrador de prédio. Avaliar versão 1.4 do UC39.

**Comment by jmatil** [comment]
Ação confirmada
