### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Item editável?

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#262]
Verificar se o item destacado na tela de evento do fluxo FA9 é realmente editável, conforme relatado na documentação.
Retificando: Os itens destacados como "DESCRIÇÃO" na tabela da tela de eventos.

![39](https://cloud.githubusercontent.com/assets/6584772/8131072/3295ee54-10ee-11e5-8e4b-7f444a1a3f9e.png)

**Comment by saires** [comment]
A informação não é editavel. Corrigido na versão 1.4 da documentação.

**Comment by jmatil** [comment]
Correção confirmada
