### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Apresentação dos Resultados

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#263]
Verificar se os eleitores já cadastrados para uma função especial deverão ser apresentados para inclusão em outras funções especiais. Segue imagem:

![39](https://cloud.githubusercontent.com/assets/6584772/8159902/804c9a80-1341-11e5-9338-d2450d03a4b8.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Favor Verificar novamente.

**Comment by saires** [comment]
Mensagem e documentação corrigida.

**Comment by jmatil** [comment]
Confirmado
