### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Importação de Dados

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#265]
A função Escrutinador não está disponível para importação de dados para outra eleição

![39](https://cloud.githubusercontent.com/assets/6584772/8169099/b28783ca-137d-11e5-81ba-fea62c2682bb.png)

**Comment by saires** [comment]
Jaílson, de acordo com a RN43, essa função não deve estar disponível para a importação e atribuição automática.

![image](https://cloud.githubusercontent.com/assets/10027679/8172687/a7ad3302-1399-11e5-8afc-0f62afbf1f72.png)

**Comment by jmatil** [comment]
Conferir o título da regra: RN43 - ACUMULAR função Especial para o mesmo Eleitor
A Regra 88 - Apresentar Função Especial Configurada - relata o seguinte:

![39](https://cloud.githubusercontent.com/assets/6584772/8183178/9e36b17c-140c-11e5-8a76-400fb527f59a.png)

**Comment by saires** [comment]
Jaílson, corrigi essa dúvida entre as regras na aplicação. A caixa de seleção deve de fato exibir todas as funções cadastradas. A RN43 entra em prática caso exista o eleitor importado já esteja atribuído para alguma função do tipo Junta no mesmo pleito.

**Comment by jmatil** [comment]
Correção confirmada
