### ISSUE TITLE
SCM_CDU_007_Atribuir Função a Mesario ( Importar Dados de Outra Eleição ) - Tela ODIN

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#267]
Ao realizar o fluxo para importar dados de outra eleição conforme tela em anexo, a aplicação vai para tela do ODIN.

![1](https://cloud.githubusercontent.com/assets/9218077/8189800/210a47a8-1435-11e5-9127-92e6627abe3b.png)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by kleiberfaria** [comment]
Item verificado !
