### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Parâmetros de Pesquisa

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#268]
O sistema não está levando em conta o parâmetro idade (Mínima/Máxima) para realização da atribuição, conforme imagem anexa:

![39](https://cloud.githubusercontent.com/assets/6584772/8212847/7ce9bed6-14f4-11e5-82a7-cbc8d641d940.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Ação validada
