### ISSUE TITLE
SCM_CDU_007_Excluir da Função Eleitoral - MSG004

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#269]
Conforme os passos do fluxo do CDU_007 FA10. Excluir Eleitor da Função Eleitoral, a aplicação exibe a mensagem "MSG004 - Exclusão realizada com Sucesso" porem não está na documentação.

**Comment by saires** [comment]
Kleiber, a documentação foi corrigida. Avaliar a versão 1.4. Nela foi inserida a mensagem e invertida a tela do protótipo entre o FA10 e o FA11.

**Comment by kleiberfaria** [comment]
Obrigado Sávio. Item verificado !
