### ISSUE TITLE
CDU_SCM_004_Gerenciar_Configuração_de_Função_Especial - Acesso aos dados da Função Eleitoral

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#27]
<b>Item:</b> A função eleitoral do tipo de mesa “função especial” deve estar cadastrada na base do Elo.
<b>Dúvida:</b> Como será realizado e configurado o acesso a esta base de dados?

**Comment by VeraNakamura** [comment]
Alinhei com o Anderson, caso não esteja clara a informação solicito que seja enviado um e-mail diretamente para o Anderson para sanar as demais dúvidas técnicas. 

O Acesso será da seguinte forma:

"O acesso ao banco de dados do elo será feito diretamente conforme as outras aplicações. 
ocorre que o elo será acessado através de componentes criados especificamente para ele, chamados de domínio.Esse domínio que acessará o banco de dados.

O SCM acessará o domínio por meio do SpringService

**Comment by jadossantos** [comment]
Ok.
