### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Atribuição Eleitoral Automática

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#270]
Ao realizar o fluxo de atribuição automática e confirmar a atribuição realizada pelo sistema foi constatado que está gerando funções a mais do que a atribuída. Segue imagem:

![39](https://cloud.githubusercontent.com/assets/6584772/8213312/653eda52-14f7-11e5-939d-21e92470e135.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Correção confirmada
