### ISSUE TITLE
SICEL_CDU_007_Consultar Atribuição de Função por Zona Eleitoral - Interface do fluxo

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#271]
No fluxo FA11. Consultar Atribuição de Função por Zona Eleitoral, a [ Interface do fluxo de eventos FA10 ],  esta referenciando o fluxo [FA10. Excluir Eleitor da Função Eleitoral] e não o fluxo FA11.

**Comment by saires** [comment]
Kleiber, a documentação foi corrigida. Avaliar a versão 1.4. Nela foi inserida a mensagem e invertida a tela do protótipo entre o FA10 e o FA11.

**Comment by kleiberfaria** [comment]
Obrigado Sábio. Item verificado !
