### ISSUE TITLE
CDU_SCM_039_Atribuir Funcao Especial ao Eleitor - Apresentação das informações

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#273]
Verificar que os itens destacados na documentação só serão apresentados caso o ator realize a importação com sucesso.

![39](https://cloud.githubusercontent.com/assets/6584772/8216244/be1ccd0a-150b-11e5-87ad-6d8aa8e1ec48.png)

**Comment by saires** [comment]
Alteração do FA 1, alteração do passo 1.5 para apresentar a listagem estava erroneamente sendo exibida do passo 1.1.
Avaliar versão 1.5 do UC39.

**Comment by jmatil** [comment]
Correção validada
