### ISSUE TITLE
SCM_CDU_007_Consultar Atribuição de Função por Zona Eleitoral - Tela do fluxo

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#274]
Conforme telas em anexo, após o fim do fluxo, o sistema apresenta a tela de "Atribuição de Função Eleitoral" e não a de Consulta de Atribuição de Eleitores por Zona Eleitoral.

![1](https://cloud.githubusercontent.com/assets/9218077/8216391/b3304f74-150c-11e5-9efa-a472cd67bbfd.png)

![2](https://cloud.githubusercontent.com/assets/9218077/8216405/c654122a-150c-11e5-989b-7cd37c424adf.png)

**Comment by saires** [comment]
Validar correção.

**Comment by kleiberfaria** [comment]
Item verificado !
