### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - RN65

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#276]
O comportamento do sistema está contrariando ao item destacado na imagem anexa.

![41](https://cloud.githubusercontent.com/assets/6584772/8230389/1b8363a2-1596-11e5-841c-0bae7c03b485.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
A ação bloqueou o campo: Seção
![41](https://cloud.githubusercontent.com/assets/6584772/8253632/1e3c6f08-1668-11e5-8442-222222562853.png)

**Comment by jmatil** [comment]
Issue compreendida, pois foi selecionada a função especial.
