### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Padronização

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#278]
Padronizar a mensagem para não ocorrer pequenos retornos devido a simples divergências 

![41](https://cloud.githubusercontent.com/assets/6584772/8230963/562d821c-159b-11e5-9975-0d47ef56dba5.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
correçao validada
