### ISSUE TITLE
CDU_SCM_004_Gerenciar_Configuração_de_Função_Especial - Município e/ou Função Especial

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#28]
<b>Item:</b> FB 1.2 - O Ator informa o Município e/ou Função especial e seleciona a opção "pesquisar" [FA 2] [FA 4];
<b>Dúvida 1:</b> Será criada uma nova tabela Município ou será utilizada uma view ou algo do tipo em uma outra base ?
<b>Dúvida 2:</b> Caso o Ator preencha somente a função especial a ser pesquisada o que deverá acontecer ? Aparecer a função para todos os municípios ? Ou obrigar o preenchimento do município.

**Comment by VeraNakamura** [comment]
Dúvida 1: Para realizar a consulta será de acordo com o que foi definido para acessar o Elo.
A tabela de Município, Local de Votação, Seção são pertencentes a base do Elo.

Dúvida 2: O passo foi alterado, obrigatoriamente deverá informar o município.

**Comment by jadossantos** [comment]
Ok.
