### ISSUE TITLE
CDU_SCM_007_Atribuir Funcao Eleitoral a Mesario - Exclusão de eleitor nomeado ad hoc

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#280]
O sistema não está permitindo a exclusão de eleitor com NOMEAÇÃO AD-HOC

![41](https://cloud.githubusercontent.com/assets/6584772/8231731/e9d475f2-15a0-11e5-8370-80dda915cb6b.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Correção validada
