### ISSUE TITLE
SCM_CDU_007_Atribuir Função Especial a Eleitor (Importar dados de outra Eleição) - ODIN

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#281]
Ao realizar a importação de dados:
Pleito Eleitoral: 2º Turno >  MRJ > IMPORTAR, aplicação esta direcionando para o ODIN 

![1](https://cloud.githubusercontent.com/assets/9218077/8232107/81dcb696-15a3-11e5-9569-da93b6f5a6fd.png)

![2](https://cloud.githubusercontent.com/assets/9218077/8232119/a1b4c0f8-15a3-11e5-921f-8318005af23f.png)

**Comment by saires** [comment]
Gentileza validar correção.

**Comment by kleiberfaria** [comment]
Item verificado !
![plano de teste_importar dados mrj](https://cloud.githubusercontent.com/assets/9218077/8257759/622b6afc-1686-11e5-9bd7-68213c4820a7.png)

**Comment by kleiberfaria** [comment]
Adicionar a informação da mensagem no plano de teste.
