### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - FA2 Excluir Evento

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#285]
As Mensagens disponibilizadas ao excluir eventos possíveis deverão ser emitidas juntas?

![41](https://cloud.githubusercontent.com/assets/6584772/8236803/1be339b4-15c1-11e5-80f5-113bab3c1a42.png)

**Comment by jmatil** [comment]
Exclusão do Evento CONVOCAÇÃO

![411](https://cloud.githubusercontent.com/assets/6584772/8238347/6e6ceb6c-15cb-11e5-80ab-4f5e227bfbd5.png)

**Comment by saires** [comment]
A primeira tela ocorre porque além de excluir ele realiza a pesquisa com o último filtro utilizado, como se trata do último eleitor, ele excluir os eventos e realiza a pesquisa, não encontrando nada. A segunda tela não consegui simular.

**Comment by jmatil** [comment]
Compreendido
