### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Eventos RN70

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#286]
Há restrição para que os eventos destacados na imagem não possam aparecer na aplicação

![411](https://cloud.githubusercontent.com/assets/6584772/8237421/8e50d9b2-15c5-11e5-9e97-cdeb90f4c9a1.png)

**Comment by saires** [comment]
Observar a RN85:

![image](https://cloud.githubusercontent.com/assets/10027679/8246913/82793bcc-161d-11e5-8e5a-4412db49f972.png)

**Comment by jmatil** [comment]
Compreendido
