### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Pesquisa por Inscrição

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#288]
O sistema não está levando em consideração somente o número de inscrição, as atribuições de mesa

![41](https://cloud.githubusercontent.com/assets/6584772/8240473/344970aa-15d9-11e5-896d-0329576a511d.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
CORREÇÃO CONFIRMADA
