### ISSUE TITLE
CDU_SCM_004_Gerenciar_Configuração_de_Função_Especial - Administrador de Prédio

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#29]
<b>Item:</b> Administrador de Prédio
<b>Sugestão:</b> Poderia vir representado por um botão desabilitado e não somente um label, como aparece na descrição da tela.

**Comment by VeraNakamura** [comment]
Isso gerou uma polêmica, a primeira vez era um botão desabilitado, mas tive que alterar 3 vezes para chegar nesse padrão, então acho melhor não alterar.

**Comment by jadossantos** [comment]
Ok.
