### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Motivo da dispensa

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#290]
O sistema exige o motivo da dispensa, mas não está gravando no resultado

![41](https://cloud.githubusercontent.com/assets/6584772/8253479/d448cfd2-1666-11e5-8169-1bb7c3733c9e.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Correção confirmada
