### ISSUE TITLE
CDU_SCM_005_Gerenciar Criterio de Selecao e Base de Eleitores Convocaveis - Campo Pesquisar

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#292]
A exceção emitida na ação do campo pesquisar mesmo não informando dados está correta? Pois o campo não foi preechido, apenas acionado o botão.

![5](https://cloud.githubusercontent.com/assets/6584772/8255403/269a3fdc-1676-11e5-8aed-7c0166e319ca.png)

**Comment by saires** [comment]
Foi criado o FE10 e invocado no passo 3.2 do FA3.
Avaliar versão 1.7 do UC05.

**Comment by jmatil** [comment]
alteração confirmada
