### ISSUE TITLE
CDU_SCM_005_Gerenciar Criterio de Selecao e Base de Eleitores Convocaveis - Seleção Manual

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#294]
O sistema não está executando a seleção manual

![5](https://cloud.githubusercontent.com/assets/6584772/8262088/183cd910-16a6-11e5-80af-9ef1b47d377d.png)

**Comment by saires** [comment]
Validar correção.

**Comment by jmatil** [comment]
Correção validada
