### ISSUE TITLE
FLUXO ALTERNATIVO 3

### ISSUE THREAD

**Issue by wfalcao** [islssa/SCM#3]
COMO SABEREMOS SE EXISTE ALGUM ELEITOR VINCULADO (QUAL SISTEMA/APLICAÇÃO/BASE DEVEMOS VERIFICAR/ATUALZIAR)? 

QUAIS SÃO AS NECESSIDADE QUE O ATOR PODE ALTERAR NO CASO DE ALTEAÇÃO DA MESA?

**Comment by danimendonca** [comment]
A atribuição será feita pelo SCM através do caso de uso "Atribuir Função Eleitoral".

A base utilizada é do próprio SCM.

O ator poderá alterar a qualquer momento a configuração da MRV, independente de eleitores atribuídos (verificar regras descritas no documento RMG_SCM).
