### ISSUE TITLE
CDU_SCM_004_Gerenciar_Configuração_de_Função_Especial - Exibição do botão Quantidade por Local de Votação

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#30]
<b>Item:</b> CDU004 - FA3 O Fluxo inicia quando o ator com o perfil “Zona Eleitoral” seleciona a opção Quantidade por Local de Votação através do Fluxo básico (FB).
<b>Dúvida:</b> O botão para acionar a função Quantidade por Local de Votação será exibido mesmo para um perfil diferente de “Zona Eleitoral”?

**Comment by VeraNakamura** [comment]
Somente será exibido para o perfil "Zona Eleitoral".
O perfil TRE apenas terá a opção de consulta do quantitativo.

**Comment by jadossantos** [comment]
Ok.
