### ISSUE TITLE
CDU_SCM_004_Gerenciar_Configuração_de_Função_Especial - Botão Limpar

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#31]
<b>Item:</b> Limpar na descrição de campos da interface do fluxo de eventos F5: Apaga as informações preenchidas pelo ator.
<b>Dúvida:</b> Os campos que deverão ser apagados incluem os campos de filtro ? Os números com as quantidades deverão ser zerados mesmo? ou podem apenas voltar para os valores que constam na base ?

**Comment by VeraNakamura** [comment]
Neste caso limpará apenas a quantidade digitada de forma que serão apresentados os valores recuperados da base.
Os filtros como Município e Local de Votação não serão apagados.

**Comment by jadossantos** [comment]
Ok.
