### ISSUE TITLE
CDU_SCM_004_Gerenciar_Configuração_de_Função_Especial- Descrição das regras vinculadas ao campo Zona Eleitoral

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#32]
<b>Item:</b> Descrição das regras vinculadas ao campo Zona Eleitoral presente na interface do Fluxo Alternativo 6 do CDU004.
<b>Observação:</b> Falta definir o número e a descrição da regra que deverá explicar que serão recuperadas as Zonas Eleitorais correspondentes ao TER (TRE ?).

**Comment by VeraNakamura** [comment]
A regra correspondente é a 75. A última versão do documento atualizada em 27/05, contempla tal regra.

**Comment by jadossantos** [comment]
Ok.
