### ISSUE TITLE
CDU_SCM_004_Gerenciar_Configuração_de_Função_Especial - Descrição do campo Local de Votação

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#33]
<b>Inconsistência:</b> Descrição do campo Local de Votação aparece na tabela com a descrição dos campos mas não aparece na tela com a interface para o fluxo alternativo 6 do CDU 004.
<b>Sugestão:</b> Verificar se a tela deve incluir o novo campo como filtro ou se esta descrição deve sair da descrição dos campos.

**Comment by VeraNakamura** [comment]
é erro e o caso de uso foi ajustado para a exclusão dos campos referente ao local de votação.
Aproveitei e atualizei o passo FA6.1 item "Quantidade por local de votação", pois fazia referência ao fluxo FA6 e o correto é o fluxo FA7.

**Comment by jadossantos** [comment]
Ok.
