### ISSUE TITLE
CDU_SCM_004_Gerenciar_Configuração_de_Função_Especial - Campos da lista exibida no Fluxo Alternativo 6 do CDU 004

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#34]
<b>Inconsistência:</b> Município e  Local de Votação aparecem descritos como campos da lista exibida no Fluxo Alternativo 6 do CDU 004, no entanto a tela não exibe estes campos. O primeiro não aparece na interface e o último provavelmente foi confundido com o campo Função Especial.

**Comment by VeraNakamura** [comment]
Corrigido de acordo com o erro #33.

**Comment by jadossantos** [comment]
Ok.
