### ISSUE TITLE
CDU_SCM_004_Gerenciar_Configuração_de_Função_Especial - Descrição do campo Local de Votação na lista

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#35]
<b>Inconsistência:</b> Descrição do campo Local de Votação na lista exibida para o Fluxo Alternativo, aparece como Função que serve de apoio ...
<b>Sugestão:</b> Trocar descrição para Unidade de divisão territorial e de divisão administrativa de determinados países.

**Comment by VeraNakamura** [comment]
Documento ajustado.

**Comment by jadossantos** [comment]
Ok.
