### ISSUE TITLE
CDU_SCM_005_Gerenciar_Criterio_de_Selecao_e_Base_de_Eleitores_Convocaveis - o campo "Inclusive Voluntário/ Indicado"

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#36]
<b>Item:</b> Descrição do campo Somente Voluntário no Fluxo Básico:</b>
<b>Inconsistência:</b> Na descrição das Regras Vinculadas, o texto diz apenas que o campo "Inclusive Voluntário/ Indicado" deve ser desabilitada, no entanto na RN030 o texto diz :</b> "Neste caso, os demais filtros (critérios) não poderão estar disponíveis para seleção."
<b>Dúvida:</b> Todos os campos ou somente o campo inclusive será desabilitado ? O mais correto seria que todos os outros campos ficassem desabilitados.

**Comment by VeraNakamura** [comment]
Caso de uso corrigido deixando apenas na coluna regras vinculadas a RN 30 para o campo "Somente Voluntário".

**Comment by jadossantos** [comment]
Ok.
