### ISSUE TITLE
CDU_SCM_005_Gerenciar_Criterio_de_Selecao_e_Base_de_Eleitores_Convocaveis - Campo Ocupações Convocáveis

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#37]
<b>Item:</b> Descrição do campo Ocupações Convocáveis
<b>Inconsistência:</b> Descrição das Regras Vinculadas aparece como "Não se aplica", quando deveria ser RN 034

**Comment by VeraNakamura** [comment]
Corrigido e respondido de acordo com o item #38

**Comment by jadossantos** [comment]
Ok.
