### ISSUE TITLE
CDU_SCM_005_Gerenciar_Criterio_de_Selecao_e_Base_de_Eleitores_Convocaveis - Campo Ocupações não Convocáveis

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#38]
<b>Item:</b> Descrição do campo Ocupações não Convocáveis
<b>Inconsistência:</b> Descrição das Regras Vinculadas aparece como "Não se aplica", quando deveria ser RN 035

**Comment by VeraNakamura** [comment]
Foi corrigido para contemplar as regras de negócio RN034 e RN035, nos fluxos de eventos FB1 e FA2.

**Comment by jadossantos** [comment]
Ok.
