### ISSUE TITLE
CDU_SCM_005_Gerenciar_Criterio_de_Selecao_e_Base_de_Eleitores_Convocaveis - Busca de eleitores convocáveis

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#39]
<b>Observação:</b> O critério de busca de eleitores convocáveis será realizado para aqueles domiciliados na mesma zona eleitoral do usuário.
Na RN40 temos:</b>  "Serão listadas todas as Seções correspondentes a Zona Eleitoral do usuário logado."
Já segundo a RN 39 :</b> "Ao final do processamento o sistema deverá apresentar um quantitativo de eleitores por seção. Neste caso o agrupamento será por município e por local de votação."
A interface mostra o município e o local de votação como não editáveis, fixos.
Município e Local de Votação não deveriam também estar presentes na listagem do quantitativo ? (Como colunas da tabela) e não fixos (não editáveis) como exibe a especificação de interface, uma vez que a pesquisa é feita com base na zona eleitoral do usuário e uma zona pode ser composta por parte de um, por um ou por muitos municípios.
<b>Dúvida:</b> Cada zona terá um critério de seleção?
<b>Dúvida:</b> A opção de selecionar eleitores manualmente, será dada somente na primeira vez que o critério for gerado ? é o que sugere a especificação de interface.

**Comment by VeraNakamura** [comment]
Dúvida 1: Sim cada Zona Eleitoral terá um critério de seleção para trabalhar com a sua respectiva base de eleitores convocáveis.

Dúvida 2: A seleção Manual estará disponível toda vez que o critério de seleção também estiver disponível.

Na verdade o Agrupamento das estatísticas se dará por Município e Local de votação. A listagem correspondente de seção, pela idade,  pela escolaridade.....e assim sucessivamente será repetido por Município.

O Critério são filtros que serão utilizados por todos os Municípios/Local de Votação vinculados a Zona Eleitoral.

**Comment by jadossantos** [comment]
Ok.
