### ISSUE TITLE
LOG

### ISSUE THREAD

**Issue by wfalcao** [islssa/SCM#4]
COMO DEVERÁ SER A POLITICA DE LOG?

(ONDE O MESMO DEVERÁ SER SALVO/ARMAZENADO)

**Comment by danimendonca** [comment]
A princípio, será armazenado na base de dados do SCM.
Neste primeiro momento não temos uma funcionalidade para consultar o log, mas foi solicitado que as operações inclusão, alteração e exclusão grave o log,
