### ISSUE TITLE
CDU_SCM_007_Atribuir_Funcao_Eleitoral_a_Mesario - Prazo limitador para as atribuições 

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#40]
<b>Dúvida :</b> Haverá um prazo limitador para as atribuições e alterações nas funções atribuídas aos eleitores ? Até que momento estas poderão ser realizadas.

**Comment by VeraNakamura** [comment]
A manipulação destas informações será controlada pelo pleito eleitoral. Conforme o pleito selecionado, apenas estará disponível as opções de consultas/relatórios sem a possibilidade de configurar, incluir, excluir e alterar funções eleitorais bem como Atribuição de funções aos eleitores.

**Comment by jadossantos** [comment]
Ok.
