### ISSUE TITLE
CDU_SCM_007_Atribuir_Funcao_Eleitoral_a_Mesario - Comportamento da exclusão

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#41]
<b>Dúvida:</b> A ação de exclusão da atribuição será física ou lógica ?

**Comment by VeraNakamura** [comment]
Apenas para eleitores com situação de atribuição = 'Atribuído' poderá ser excluído fisicamente, para os demais caso a exclusão não será física porque será necessário gerenciar os eventos de cada eleitor.

**Comment by jadossantos** [comment]
Ok.
