### ISSUE TITLE
CDU_SCM_007_Atribuir_Funcao_Eleitoral_a_Mesario - Alinhamento da coluna ações

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#42]
<b>Sugestão:</b> Geralmente a coluna de ações aparece na direita da tabela, existe alguma regra que exija o alinhamento à esquerda apresentado nas interfaces.

**Comment by VeraNakamura** [comment]
Não foi exigência do cliente, mas pelo fato de outros CDUs também apresentar a coluna ações do lado esquerdo.
Vou ver com o cliente se há alguma restrição de mudanças.

**Comment by jadossantos** [comment]
Ok.
