### ISSUE TITLE
CDU_SCM_007_Atribuir_Funcao_Eleitoral_a_Mesario - Promoção de cargo

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#43]
<b>Dúvida:</b> Existe uma regra que defina melhor o comportamento de Promoção ? Haverá a possibilidade de promoções em cascata? Por exemplo, ao se promover um mesário na terceira função, o funcionário da segunda função será também automaticamente promovido? A promoção só ocorre para o cargo de presidente da mesa?

**Comment by VeraNakamura** [comment]
Irei ajustar a RN37 que é referente a promoção.

Para que o processo de promoção esteja habilitado é necessário que a função eleitoral Presidente não tenha eleitor atribuído, ou seja, função vaga. Além disso deverá validar se para as demais funções como: Primeiro Mesário, Segundo Mesário, Suplente e assim sucessivamente se tem eleitor vinculado. A partir do momento que é feita a promoção todos os eleitores que estejam vinculados as demais função serão promovidos.
Exemplo: Primeiro Mesário, passará a ser Presidente, Segundo Mesário passará a ser Segundo Mesário.... e um ou vários cargos ficarão vagos quando utilizado a promoção em cascata.

Outro caso que poderá ocorrer: Presidente, Primeiro Mesário, Segundo Mesário sem eleitor e somente o cargo de Suplente com Eleitor  vinculado. Neste caso ao promover o Eleitor ele será atribuído para a função de Presidente diretamente.

**Comment by jadossantos** [comment]
Ok.
