### ISSUE TITLE
CDU_SCM_037_Consultar_Pleito_Eleitoral - Situação dos pleitos

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#44]
<b>Inconsistência:</b> Os pleitos deverão possuir as suas respectivas situações.
<b>Proposta:</b> Definir junto ao cliente, se há a necessidade de manter o histórico das situações por pleito. Caso não haja esta necessidade, ratificar se um pleito cancelado poderá ser reativado ou se será necessário configura-lo novamente.

**Comment by VeraNakamura** [comment]
A manipulação das informações de pleito não é controlado pelo SCM, apenas recuperamos do Elo as situações dos pleitos eleitorais, ainda está pendente de definição por parte do cliente a relação de pleito eleitoral e processo eleitoral.

**Comment by jadossantos** [comment]
Ok.
