### ISSUE TITLE
CDU_SCM_038_Consultar_Municipio_e_Local_de_Votacao - Fluxo Alternativo incompleto

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#45]
<b>Inconsistência:</b> No FA 1, falta a referência ao FE 4.
<b>Proposta:</b> Definir junto ao cliente, se há relação entre os FA 1 e o FE 4.

**Comment by VeraNakamura** [comment]
Erro que foi corrigido.
Chamada do fluxo de exceção FE3 no passo FB1.3;
Chamada do fluxo de exceção FE4 no passo FA1.3.

**Comment by jadossantos** [comment]
Ok.
