### ISSUE TITLE
CDU_SCM_038_Consultar_Municipio_e_Local_de_Votacao - Botão voltar

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#46]
<b>Inconsistência:</b> Na tabela “Comandos” do FB1 existe uma referência ao botão “Voltar” que não é apresentado na proposta de layout.
<b>Proposta:</b> Remover o item da tabela.

**Comment by VeraNakamura** [comment]
Corrigido.

**Comment by jadossantos** [comment]
Ok.
