### ISSUE TITLE
CDU_SCM_038_Consultar_Municipio_e_Local_de_Votacao - Dois campos com o mesmo nome

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#48]
<b>Inconsistência:</b> Na tabela “Campos” do FA1 existem dois labels com mesmo nome (Número de Identificação) e definição. É isso mesmo? Qual é a diferença entre eles?

**Comment by VeraNakamura** [comment]
O primeiro número de identificação é referente ao do Município;
O Segundo número de identificação é referente ao Local de  Votação;

**Comment by jadossantos** [comment]
Ok.
