### ISSUE TITLE
CDU_SCM_039_Atribuir_Funcao_Especial_ao_Eleitor - Campo Funções Eleitorais

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#49]
<b>Inconsistência:</b> No item FB 1.3 Campo Funções Eleitorais aparece na interface como Funções Especiais.
<b>Proposta:</b> O CDU_039 diz que a busca de eleitores deve ser realizada por município e referencia a RN24 que diz :</b> “O Sistema deverá recuperar todos os eleitores da referida Seção eleitoral”. Provavelmente a busca deverá ser realizada por município, portanto deverá haver alguma alteração no texto da regra ou a criação de uma regra mais específica.

**Comment by VeraNakamura** [comment]
Esta parte da regra é para o caso de uso CDU007.
Para o caso de uso CDU039, apenas deverá o final correspondente a função especial.
Segue o trecho da regra que deve ser implementada para o CDU039. Mesmo assim alterei o subtítulo para "Atribuir eleitor a função especial".

Função Especial
Para a função especial, o sistema deverá recuperar todos os eleitores que são vinculados ao Município e não ao local de votação.
Também na primeira listagem deverá apresentar somente os eleitores que ainda não estejam atribuídos para uma função especial do tipo “Junta eleitoral” e “Administrador de Prédio”.

**Comment by jadossantos** [comment]
Ok.
