### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_Falta o nome do sistema na tela.

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#5]
Na tela Configuração de Mesa Receptora de Votos não está sendo apresentado o nome do sistema "Sistema de Configuração de Mesários - SCM".
Esse título deve aparecer centralizado e em negrito.
Favor verificar a tela no caso de uso.

**Comment by jadossantos** [comment]
O padrão (css) do layout do sistema ainda não foi definido. Entramos em contato com o responsável da criação do CSS e estamos aguardando uma resposta. Iremos tratar isso como uma melhoria.

**Comment by jadossantos** [comment]
O Título já foi inserido.

**Comment by marasb** [comment]
O título foi inserido corretamente.
Em relação à centralização dos campos na tela, não precisa mais ser feito, visto que o Layout deve seguir o padrão do SPCA e SJUR e nesses sistemas os campos são alinhados à esquerda.
Já conversei com a Vera em relação a essa situação e ela concordou.
Sendo assim o bug será fechado.
