### ISSUE TITLE
CDU_SCM_039_Atribuir_Funcao_Especial_ao_Eleitor - Nova consulta no sistema ELO

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#50]
<b>Sugestão:</b> Referente à RN28 que sugere uma nova consulta no sistema ELO, seria mais interessante que a experiência em pleitos deva ser calculada e importada juntamente quando da importação dos eleitores convocáveis;

**Comment by VeraNakamura** [comment]
Não é possível recuperar o histórico de participações de eleições no SCM, pois toda esta informação está guardada na base do Elo.

**Comment by jadossantos** [comment]
Ok.
