### ISSUE TITLE
CDU_SCM_041_Gerenciar_Evento - Exibição do botão dispensa

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#51]
<b>Dúvida:</b> Na interface o botão de excluir aparece somente para o evento Dispensa, esta ação estará disponível para todos os eventos correto?

**Comment by VeraNakamura** [comment]
Sempre aparecerá a opção de exclusão para o último evento.
Mesmo assim o caso de uso esta sendo reformulado para contemplar várias regras de evento, motivo de evento, e o que é feito quando um evento é lançado. Tudo é refletido nos CDUs 007 e 039.

**Comment by jadossantos** [comment]
Ok.
