### ISSUE TITLE
CDU_SCM_040_Solicitar_e_Autorizar_Eleitor - Duplicidade do número de documento

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#52]
<b>Dúvida:</b> Duplicidade do número de documento utilizado para autorizar/não autorizar um eleitor.
<b>Proposta:</b> Verificar junto ao cliente, se o número de documento utilizado para autorizar/não autorizar um eleitor, pode ser o mesmo para vários eleitores. Caso não possa, não será possível autorizar/não autorizar vários eleitores simultaneamente.

**Comment by VeraNakamura** [comment]
Um documento servirá para autorizar/não autorizar vários Eleitores.

**Comment by jadossantos** [comment]
Ok.
