### ISSUE TITLE
CDU_SCM_040_Solicitar_e_Autorizar_Eleitor - Ícone ”Excluir”

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#53]
<b>Dúvida:</b> Solicitação dos eleitores para a Zona Eleitoral de Inscrição.
<b>Proposta:</b> Verificar junto ao cliente, se o ícone ”Excluir”, presente na “Lista de Eleitores pesquisados e que serão solicitados”, ao ser acionado, escolhe o eleitor que será solicitado. Caso seja, sugiro que altere o ícone para um ícone mais apropriado para a ação e atualize a tabela “Lista de Eleitores Solicitados”, logo após aciona-lo.

**Comment by VeraNakamura** [comment]
Esta dúvida é referente ao fluxo de eventos FA2? Logo após preencher a inscrição as informações do eleitor a ser solicitado aparece em uma lista com o ícone "X"? Você diz alterar este ícone. A problemática é que o cliente reclama das várias ações e cliques, portanto não foi colocada a opção para seleção e um botão de excluir. Tentei diminuir a quantidade de cliques.
Há alguma limitação em fazer do jeito que foi especificado?

**Comment by jadossantos** [comment]
Ok.
