### ISSUE TITLE
CDU_SCM_040_Solicitar_e_Autorizar_Eleitor - Solicitação dos eleitores

### ISSUE THREAD

**Issue by jadossantos** [islssa/SCM#54]
<b>Dúvida:</b> Solicitação dos eleitores para a Zona Eleitoral de Inscrição.
<b>Proposta:</b> Verificar junto ao cliente, se ao solicitar um eleitor da própria zona do usuário logado, automaticamente esta solicitação será aprovada.

**Comment by VeraNakamura** [comment]
A solicitação será exclusivamente de eleitores de outra zona eleitoral. Neste caso, posso criar uma msg de alerta caso o CDU não contemple, informando que o Eleitor está vinculado a Zona eleitoral, portanto não precisa ser solicitado. Como este CDU é da Iteração 3 posso e não foi homologado posso alterar sem problemas.

**Comment by jadossantos** [comment]
Ok.
