### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Execução do Fluxo E1

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#56]
Favor verificar o comportamento do sistema, pois ao informar uma "Função Especial" não existente, juntamente com dados válidos para os campos município e acionar a opção "Pesquisar" o sistema não emite a mensagem conforme relatada na documentação. Apenas direciona o usuário para a tela do sistema "Odin". Segue imagem:

![issue](https://cloud.githubusercontent.com/assets/6584772/5248625/ac1d80d4-7963-11e4-8f8a-f94e4aa18539.png)

**Comment by saires** [comment]
Correção realizada.
Favor verificar.

**Comment by jmatil** [comment]
Item verificado. Segue imagem de confirmação

![issue](https://cloud.githubusercontent.com/assets/6584772/5249992/3511ffae-796f-11e4-88a3-28aebed38400.png)
