### ISSUE TITLE
CDU_SCM_038_Consultar_Municipio_e_Local_de_Votacao - MSG Divergente da Documentação

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#57]
Prezados,

Realizando uma pesquisa no campo ["Número de identificação"] com um número não cadastrado, o sistema apresenta a MSG029 sendo que deveria apresentar a MSG028 conforme o FE1. 

![2-msg do sistema nao bate com a documentacao msg028](https://cloud.githubusercontent.com/assets/9218077/5249661/263776b0-796c-11e4-9801-f38bab297f73.jpg)

![2 2](https://cloud.githubusercontent.com/assets/9218077/5249662/2b62e296-796c-11e4-894a-59993db0b084.jpg)

**Comment by saires** [comment]
Exibição de mensagem corrigida.

**Comment by kleiberfaria** [comment]
Item verificado. Obrigado
