### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuração de Função Especial - Inexistência de fluxo

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#59]
Favor verificar a necessidade de inclusão de algum fluxo de exceção para a situação abaixo.

![issue-1](https://cloud.githubusercontent.com/assets/6584772/5342967/6c16b77c-7ee9-11e4-9f2d-1d0ebf32ecb5.png)

**Comment by espinola** [comment]
Somente o município é obrigatório, basta tratar somente este campo

**Comment by jmatil** [comment]
O problema é que este fluxo (ação) não existe na documentação

**Comment by espinola** [comment]
foi criado um fluxo de exceção de campo obrigatório

**Comment by saires** [comment]
Mensagem corrigida.
Favor, corrigir a mensagem na documentação.
![image](https://cloud.githubusercontent.com/assets/10027679/5430316/a3065660-83f4-11e4-8d38-59a2cc71eb8e.png)

**Comment by espinola** [comment]
corrigido

**Comment by jmatil** [comment]
Confirmado a Correção
