### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Impossibilidade de Execução

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#60]
Favor verificar a possibilidade de emissão da mensagem 006 - "inclusão realizada com sucesso". No momento o sistema está interpretando que já existe um valor atribuido à função e emite somente a mensagem 002 - "Alteração realizada com sucesso".

![issue-2](https://cloud.githubusercontent.com/assets/6584772/5343329/66e3a172-7eec-11e4-97c6-e2a6d4106d6e.png)

**Comment by saires** [comment]
A mensagem MSG006 é disparada quando a quantidade de uma função é alterada de 0 para mais.
A mensagem MSG002 é disparada quando a quantidade de uma função é alterada de +1 para mais.
Sugiro utilizar uma mensagem mais genérica, ou apenas a MSG002.

**Comment by espinola** [comment]
Vamos utilizar sempre a MSG002 que foi alterada para "Operação realizada com sucesso."

**Comment by saires** [comment]
Mensagem corrigida.

**Comment by jmatil** [comment]
Confirmado a correção.

![corrigido](https://cloud.githubusercontent.com/assets/6584772/5397142/13eae494-813f-11e4-8222-e986a7fa42c0.png)
