### ISSUE TITLE
CDU_SCM_038_Consultar_Municipio_e_Local_de_Votação - Pesquisa local de votação - Documentação

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#61]
Prezado,

Conforme imagens em anexo, o [ FA1. Pesquisar local de votação ] na documentação "CDU_SCM_038" o sistema esta segue o fluxo que não se encontra no FA1.  

![docum_scm_1](https://cloud.githubusercontent.com/assets/9218077/5343672/479e6f2e-7eef-11e4-8500-2dc67119b4fd.jpg)
![docum_scm_2](https://cloud.githubusercontent.com/assets/9218077/5343673/4df9fc30-7eef-11e4-96ef-20cd94bc3571.jpg)
![docum_scm_3](https://cloud.githubusercontent.com/assets/9218077/5343675/538d8d9c-7eef-11e4-96bc-c184236a0ca9.jpg)
![docum_scm_4](https://cloud.githubusercontent.com/assets/9218077/5343679/58728204-7eef-11e4-8709-2a0a53ed6b42.jpg)

**Comment by espinola** [comment]
Documentação atualizada como conversamos, fui adicionado o FA1 no FB e criado uma precondição para FA1
