### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Informações Apresentadas

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#62]
Favor verificar se as informações que estão sendo solicitadas serão realmente aquelas que deverão ser apresentadas ao acessar a opção "Gerenciar Configuração de Função Especial" no menu principal do SCM.

![issue-3](https://cloud.githubusercontent.com/assets/6584772/5343690/6ed474da-7eef-11e4-9412-21f5fc4ab654.png)

**Comment by espinola** [comment]
esta correto pois cada UF possui um TRE então o nome sempre vai ser TRE-UF
