### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Itens Inexistentes

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#63]
1) Favor avaliar a existência de itens que são citados na documentação.
2) Verificar a interface disponível na documentação, pois há divergência entre a imagem e a solicitação de que o campo não é editável.

![issue-4](https://cloud.githubusercontent.com/assets/6584772/5344287/55bc5214-7ef5-11e4-9501-fd40bf93c9d5.png)

**Comment by saires** [comment]
Foi inserida a caixa para seleção da Zona Eleitoral para o perfil TRE. Deve ser revista a necessidade dessa caixa de seleção, uma vez que as funções são por Municipio, e não por Zona Eleitoral. 
O campo Municipio passou a ser input não editável, de acordo com a documentação.

**Comment by jmatil** [comment]
Confirmado a Implementação do Item:
![issue-24](https://cloud.githubusercontent.com/assets/6584772/5411449/b013a830-81e7-11e4-9356-751cda381c5b.png)

Enzo
poderia avaliar a situação relatada pelo Sávio? : "Deve ser revista a necessidade dessa caixa de seleção, uma vez que as funções são por Municipio, e não por Zona Eleitoral."

**Comment by espinola** [comment]
Campo não mais editável, documentação atualizada

**Comment by jmatil** [comment]
confirmado a edição
