### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Existência da Label

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#64]
Favor verificar se há necessidade de existência ou não da label destacada na documentação.

> > Documento <<
> > ![issue-5](https://cloud.githubusercontent.com/assets/6584772/5356577/4d2d9b90-7f85-11e4-9fd6-101702a4f34d.png)
> > 
> > Sistema <<
> > ![issue-6](https://cloud.githubusercontent.com/assets/6584772/5356584/639cf07e-7f85-11e4-8809-9a41323ac6a5.png)

**Comment by espinola** [comment]
vamos padronizar, colocar o titulo em tudo

**Comment by saires** [comment]
Label inserida.

**Comment by jmatil** [comment]
Confirmado a implementação da Label

![corrigido](https://cloud.githubusercontent.com/assets/6584772/5411541/a22951e2-81e8-11e4-9d9d-010b29ac1e2d.png)
