### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuração de Função Especial - Opção "Limpar"

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#65]
Favor verificar o acionamento da opção "Limpar", pois para algumas funcionalidades o sistema está direcionando o ator à pagina inicial da funcionalidade onde é apresentado os campos para a pesquisa inicial.
A simulação foi realizada logo após apresentação dos resultados na inclusão de quantitativo para a função de administrador de prédio.

**Comment by saires** [comment]
Enzo, verificar a necessidade desses botões de limpar nesse caso de uso. Segundo o UC, esse botão deve "Apaga as informações preenchidas pelo ator". A unica informação que o ator preenche são os valores de quantidade de pessoas para cada função. Limpar essas informações envolve regras atribuição de eleitores dentre outras. Sugiro a retirada ou então definir melhor essa regra.

**Comment by espinola** [comment]
A ação "Limpar", apaga as informações da grid e não as da consulta, pois esta ação só aparece quando o ator executa a pesquisa.

**Comment by saires** [comment]
O botão passou a esconder a grid. O município pesquisado permanece selecionado.

**Comment by jmatil** [comment]
Confirmado a Implementação
