### ISSUE TITLE
CDU_SCM_038_Consultar_Municipio_e_Local_de_Votação - Tela Pesquisar local de votação

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#66]
Prezados,

Conforme imagem em anexo, os campos de acordo com a tela da Interface do fluxo de eventos do CDU_SCM_038, estão fora da posição.

![tela_t](https://cloud.githubusercontent.com/assets/9218077/5358053/ca94d6fa-7f96-11e4-9600-750fdca912a4.jpg)
![tela_tt](https://cloud.githubusercontent.com/assets/9218077/5358124/9da67418-7f97-11e4-9ac3-55cf12e4d0f9.jpg)

**Comment by saires** [comment]
Corrigido. Porém, a ordem não é exatamente do protótipo. A forma atual de um abaixo do outro evita a quebra de layout entre diferentes navegadores.

**Comment by kleiberfaria** [comment]
Item verificado !
