### ISSUE TITLE
CDU_SCM_038_Consultar_Municipio_e_Local_de_Votação - Local de votação não encontrada

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#67]
Prezado,

De acordo com o [ FE4. Local de votação não encontrada ], o sistema ao vefiricar um local de votação não existente esta apresentando a msg "No records found" e não a mensagem MSG031 conforme o fluxo do CDU.

![consultarrrrrr](https://cloud.githubusercontent.com/assets/9218077/5360246/2e83c0f0-7faa-11e4-9869-67db8f292fda.jpg)

**Comment by saires** [comment]
Corrigido.

**Comment by kleiberfaria** [comment]
Item verificado
