### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuração de Função Especial - Botão ' Voltar '

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#68]
A opção ' Voltar ' disponível na funcionalidade onde é Gerenciada a ' Quantidade por Local de Votação ' deveria voltar à página anterior com os resultados que eram apresentados ou com apenas os campos para uma nova realização de pesquisa de Município? Segue imagem

![issue-8](https://cloud.githubusercontent.com/assets/6584772/5376675/614cb53a-8060-11e4-980d-ed88caae66d9.png)

**Comment by espinola** [comment]
Como o caso de uso não apresenta a necessidade de recupera a pesquisa quando o usuário retorna a tela anterior, o comportamento do sistema hoje esta correto.

**Comment by jmatil** [comment]
Compreendido.
