### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuração de Função Especial - Tamanho do Campo e Quantidade de   Caracteres Aceitos

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#69]
Favor verificar a quantidade de caracteres que deverão ser aceitos no campo 'Quantidade de Eleitores Configurados para um Determinado Local de Votação'. Atualmente o sistema está aceitando 4 (Quatro) dígitos conforme destacado na imagem abaixo.'

![issue-9](https://cloud.githubusercontent.com/assets/6584772/5376708/c6260b3c-8060-11e4-9fbb-b358aa7381c0.png)

**Comment by espinola** [comment]
documentação atualizada para 4 caracteres
