### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_Os botões não estão centralizados

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#7]
Na tela Configuração de Mesa Receptora de Votos os botões "Voltar", "Limpar" e "Salvar", não está centralizado, porém no caso de uso esses botões aparecem centralizados.

**Comment by jadossantos** [comment]
O padrão (css) do layout do sistema ainda não foi definido. Entramos em contato com o responsável da criação do CSS e estamos aguardando uma resposta. Iremos tratar isso como uma melhoria.

**Comment by marasb** [comment]
Em relação à centralização dos campos na tela, não precisa mais ser feito, visto que o Layout deve seguir o padrão do SPCA e SJUR e nesses sistemas os campos são alinhados à esquerda.
Já conversei com a Vera em relação a essa situação e ela concordou.
Sendo assim o bug será fechado.
