### ISSUE TITLE
 CDU_SCM_004_Gerenciar Configuração de Função Especial - Obrigatoriedade de apresentação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#70]
Favor verificar se a apresentação do nome do Município é realmente obrigatório ou não. Segue Imagem.

![issue-10](https://cloud.githubusercontent.com/assets/6584772/5376735/0cf9736e-8061-11e4-9d48-4d54c0cf7518.png)

**Comment by espinola** [comment]
Vamos seguir a tabela de descrição, obrigatório = "Não"
