### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuração de Função Especial - Caixa de Seleção - Zona Eleitoral

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#71]
Verificar a inexistência da 'Caixa de Seleção' Zona Eleitoral exigida pela documentação.

![issue-11](https://cloud.githubusercontent.com/assets/6584772/5376756/47fa7bfc-8061-11e4-87e7-ec8b4de2bc52.png)

**Comment by saires** [comment]
Caixa de seleção inserida. Porem essa mudança não faz nada no sistema. Deve ser revista a necessidade dessa caixa de seleção, uma vez que as funções são por Municipio, e não por Zona Eleitoral.

**Comment by jmatil** [comment]
Implementação confirmada
Enzo
poderia ser revistas esta situaçãor relatada pelo Sávio?

**Comment by espinola** [comment]
Campo não mais editavel, documentação atualizada

**Comment by jmatil** [comment]
Ação confirmada
