### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuração de Função Especial - Itens Apresentáveis

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#72]
Há alguma informação relacionada ao 'Pleito Eleitoral' que deveria ser apresentada no resultado da pesquisa ou na documentação está faltando os outros itens: Função Especial, Município e Local de Votação?

![issue-12](https://cloud.githubusercontent.com/assets/6584772/5376775/7c9a4522-8061-11e4-8e51-bed9b969dd2e.png)

**Comment by espinola** [comment]
Documentação atualizada foi retirado o capo Pleito Eleitoral do passo FA3.1 pois o mesmo esta sendo descrito errado.

**Comment by jmatil** [comment]
Confirmado a Exclusão e verificado na documentação atualizada
