### ISSUE TITLE
CDU_SCM_038_Consultar_Municipio_e_Local_de_Votacao - Consultar Local de Votação MSG028

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#73]
Prezados,
Ao consultar um [ "Número de Identificação" ] inexistente conforme o FE1 e ao preencher campo, deve apresentar a MSG028 

![1](https://cloud.githubusercontent.com/assets/9218077/5381552/8e68cf26-8089-11e4-8cc0-0fc9ef06ab36.jpg)

**Comment by saires** [comment]
Corrigido.

**Comment by kleiberfaria** [comment]
Item verificado !
