### ISSUE TITLE
CDU_SCM_038_Consultar_Municipio_e_Local_de_Votacao - FE2 da Documentação

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#74]
Prezado,

O ["FE2. Município pertencente a outra Zona Eleitoral"] do CDU 038, não se aplica atualmente para a devida aplicação.

![3](https://cloud.githubusercontent.com/assets/9218077/5381612/2f8b1738-808a-11e4-956d-3bba7e0d55ca.jpg)

**Comment by saires** [comment]
Enzo, após análise verifiquei que de fato esse fluxo existe. Favor reverter essa alteração e manter como estava na documentação. A aplicação está tratando isso agora.

**Comment by kleiberfaria** [comment]
Prezados,
Então o fluxo vai existir na aplicação? Foi realizado já o script de teste e as evidências sem o FE 2

**Comment by espinola** [comment]
Ja retornei o fluxo para o caso de uso

**Comment by kleiberfaria** [comment]
Item verificado
