### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Label

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#75]
Favor verificar que a 'label' exigida pela documentação não está sendo apresentada no sistema.

![issue-13](https://cloud.githubusercontent.com/assets/6584772/5392795/6b6c459c-8111-11e4-852f-faec6628a4c9.png)

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Label não implementada até o momento.

![corrigido](https://cloud.githubusercontent.com/assets/6584772/5409484/f9c538d8-81d1-11e4-82f7-fdac7c112c3a.png)

**Comment by jmatil** [comment]
Confirmada a Implementação
