### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Botão Inexistente na documentação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#76]
Favor verificar a inclusão deste 'Botão' destacado na imagem, pois na documentação este item não é apresentado.

![issue-14](https://cloud.githubusercontent.com/assets/6584772/5392877/72939338-8112-11e4-88bf-e6ce0d6665c1.png)

**Comment by espinola** [comment]
O correto e igual está no caso de uso.

**Comment by saires** [comment]
Esse botão é para ser apresentado caso o usuário deseje consultar a configuração de mesa receptora de justificativa (FA1). Porém, esse fluxo e o FB se iniciam da mesma forma: "Este fluxo se inicia quando o ator seleciona a opção Gerenciar Configuração de Mesa Receptora de Justificativas no menu principal do SCM ". Dessa forma não há como tratar a exibição desse botão, pois não tem como saber se o usuário deseja inserir uma função ou apenas consultar. Sugiro alterar o menu acrescentando dois subníveis ao menu MRJ: MRJ > Consultar e MRJ > Alterar. O mesmo vale para MRV.

**Comment by kleiberfaria** [comment]
Foi verificado a retirada do item relatado na issue

![corrigido](https://cloud.githubusercontent.com/assets/9218077/5776591/fc822684-9d70-11e4-8f8a-2cb9d4d2b707.PNG)
