### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Composição

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#77]
Favor verificar  a disponibilidade de apresentação da composição da mesa recepetora de justificativa, pois ao acessar a funcionalidade com o perfil TRE-ES, acessar as funcionalidades do sistema e retornar ao pertil 'Zona 0001' o sistema não apresenta mais a composição que antes era apresentada ao usuário.

![issue-15](https://cloud.githubusercontent.com/assets/6584772/5393017/fc6a22ec-8113-11e4-94e6-2dec5955443b.png)

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Correção confirmada.

![corrigido](https://cloud.githubusercontent.com/assets/6584772/5409448/93e3e42e-81d1-11e4-9e67-4fab1cb14943.png)
