### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Consulta à configuração

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#78]
Preciso de auxílio para visualização da consulta da configuração da Mesa Receptora de Justificativa, pois não estou encontrando o caminho que leva a esta tela conforme relatado na documentação disponibilizada para a realização dos testes. Foi implementado?

![issue-16](https://cloud.githubusercontent.com/assets/6584772/5393218/68efdbc6-8116-11e4-9e0f-24e138c478aa.png)

**Comment by saires** [comment]
Esse fluxo e o FB se iniciam da mesma forma: "Este fluxo se inicia quando o ator seleciona a opção Gerenciar Configuração de Mesa Receptora de Justificativas no menu principal do SCM ". Dessa forma não há como tratar a exibição desse tela, pois não tem como saber se o usuário deseja inserir uma função ou apenas consultar. Sugiro alterar o menu acrescentando dois subníveis ao menu MRJ: MRJ > Consultar e MRJ > Alterar. O mesmo vale para MRV.

**Comment by monicaleite** [comment]
Sávio,
Após o registro ser criado, todo acesso a ser realizado posteriormente nesse registro será considerado como edição.

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Confirmado a Implementação
![corrigido](https://cloud.githubusercontent.com/assets/6584772/5434229/a977ea1c-8436-11e4-9bff-5c84bb00ef65.png)
