### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Implementação

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#79]
Favor verificar se os itens relacionados à 'Consulta da Configuração da Mesa Receptora de Justificativas' foram implementadas para o perfil TRE, pois há divergências entre o que está apresentado e o que está disponibilizado no sistema. Segue imagem.

![issue-17](https://cloud.githubusercontent.com/assets/6584772/5393313/bff7dbac-8117-11e4-92ec-eb1e0ddbfcb6.png)

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Implementação confirmada

![corrigido](https://cloud.githubusercontent.com/assets/6584772/5409606/7476ddb0-81d3-11e4-84a9-f9182a5bfc2c.png)
