### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Disponibilidade dos Itens

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#80]
Prezados
Precisamos nos orientar em relação as funcionalidades que serão disponibilizadas para este CDU. O layout disponibilizado na documentação está com algumas divergências em relação ao que está sendo apresentado pelo sistema. Estes itens devem permanecer (seguir fielmente o que é exigido) ou devemos ignorar estes itens apresentados? Aparentemente as documentações estão desatualizadas e apresentando bastante divergência com os itens que estão diponibilizados no sistema. Segue exemplo:

![issue-18](https://cloud.githubusercontent.com/assets/6584772/5410135/a1e6a9ba-81d8-11e4-8a63-26104b028c1e.png)

**Comment by espinola** [comment]
seguir documentação

**Comment by jmatil** [comment]
Sávio
favor avaliar a situação exigida na documentação conforme relato acima.

**Comment by saires** [comment]
No que diz respeito as "setas", trata-se de componentes pré-definidos pela tecnologia utilizada (Primefaces). Essa tecnologia é pré-requisito para o projeto. O protótipo está desatualizado.

**Comment by jmatil** [comment]
Enzo
Será atualizado o protótipo disponível neste fluxo FA2 - Alterar Configuração de Mesa Receptora de Justificativas?

**Comment by espinola** [comment]
atualizado

**Comment by kleiberfaria** [comment]
OK
