### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Passos Indisponíveis

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#81]
Favor avaliar o item destacado na documentação, pois até o momento esta opção de seleção não está disponibilidade no sistema atual. Esta opção "Atualizar" deverá ser implementada?

![issue-19](https://cloud.githubusercontent.com/assets/6584772/5410413/4f648894-81db-11e4-99ab-092d2b422cf6.png)

**Comment by espinola** [comment]
Não está disponível pq? ela esta descrita como para ser utilizada ? se sim tem que manter igual descrito na documentação.

**Comment by jmatil** [comment]
Na aplicação atual não existe a opção "Alterar" para ser selecionada. O ator apenas acessa a funcionalidade diretamente. As ações de inclusão ou exclusão ("Alteração") são executadas diretamente sem um acionamento anterior conforme relatado na documentação. "Este fluxo se inicia quando o ator SELECIONA a opção 'Alterar' na consulta da MRJ".

**Comment by saires** [comment]
Corrigido.Mas não está claro na documentação que esse fluxo será executado apenas pelo perfil Zona. Foi inserido um botão para limpar. Os protótipos dessa tela na documentação não estão iguais. Deve-se atualiza-la.

**Comment by jmatil** [comment]
Implementação confirmada.
Enzo
conforme relato acima, o protótipo realmente não apresenta esta funcionalidade para o fluxo FA2 - Alterar Configuração de Mesa Receptora de Justificativas. Pergunta: Será atualizado o protótipo disponível neste caso de uso?

![issue-26](https://cloud.githubusercontent.com/assets/6584772/5433941/b2ca65c0-8433-11e4-9163-75c834c2433f.png)

**Comment by espinola** [comment]
Este fluxo esta sendo chamado no passo FA1.2, e neste passo contem o botão alterar

![image](https://cloud.githubusercontent.com/assets/8427809/5435069/e04b5054-843d-11e4-9178-73dab3f43479.png)

**Comment by jmatil** [comment]
Questão compreendida
