### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Mensagem

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#82]
Qual mensagem deverá ser emitida ao ser simulado a Alteração da Configuração de Mesa Receptora de Justificativa?

![issue-20](https://cloud.githubusercontent.com/assets/6584772/5410503/54c61310-81dc-11e4-8225-8ddc23285f22.png)

**Comment by espinola** [comment]
Seguir a documentação

**Comment by saires** [comment]
Mensagem corrigida.

**Comment by jmatil** [comment]
Confirmado a correção
