### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Caixa de Seleção

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#83]
Favor verificar a caixa de seleção (Zona Eleitoral) disponibilizada para o perfil 'TRE', pois no momento esta caixa está sem funcionalidade. 

![issue-22](https://cloud.githubusercontent.com/assets/6584772/5410797/42c992a0-81e0-11e4-8227-e22b1e56920d.png)

**Comment by saires** [comment]
As configurações da zona escolhida é carregada na tela.

**Comment by jmatil** [comment]
confirmado a implementação

![corrigido](https://cloud.githubusercontent.com/assets/6584772/5440076/97bc859a-846c-11e4-81b2-fbd41880db2a.png)
