### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Visualização

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#84]
Assim como o botão 'Excluir' que não deve está habilitado para o pertil TRE, o botão 'ALTERAR' segue a mesma solicitação: "Não está habilitado". Pergunta: Ambos devem ser apresentados?

![issue-23](https://cloud.githubusercontent.com/assets/6584772/5410987/89f1fbd4-81e2-11e4-8488-b90043e0d9df.png)

**Comment by espinola** [comment]
Seguir a documentação sempre

**Comment by jmatil** [comment]
Sávio
favor avaliar a situação acima

**Comment by saires** [comment]
Corrigido.

**Comment by jmatil** [comment]
Confirmado a implementação

![corrigido](https://cloud.githubusercontent.com/assets/6584772/5433658/d3427ade-8430-11e4-850f-6c869cbb6298.png)
