### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Campo Zona Eleiotoral

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#85]
Prezados,

Conforme documentação CDU_003, o tamanho do campo para [ Zona Eleitoral ], esta na aplicação o tamanho 1 e na documentação tamanho "3".
![1](https://cloud.githubusercontent.com/assets/9218077/5411555/de0e1f62-81e8-11e4-9d99-3285bceac35e.jpg)

![1 1](https://cloud.githubusercontent.com/assets/9218077/5411646/dcc61b4a-81e9-11e4-8ee5-a37c821c0324.jpg)

**Comment by saires** [comment]
Deve-se definir uma máscara para os campos núméricos. (completar com 0's ou não)

**Comment by espinola** [comment]
se não existe mascara não é obrigatório ter 00 para preencher o campo, ou meu ver.

**Comment by kleiberfaria** [comment]
Item verificado !
