### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Arrastar Funções Eleitorais

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#86]
Prezados,
Ao arrastar as funções eleitorais em "Selecionadas" essas opções inativas podem ser salvas no campo "Disponíveis" da aplicação conforme imagem em anexo. Ao salvar, o sistema vai para a tela do ODIN.

![1](https://cloud.githubusercontent.com/assets/9218077/5416030/daffcc2e-8212-11e4-8e46-c836f5ff0feb.jpg)

**Comment by saires** [comment]
Esse componente do projeto possui esse bug. A ação pelas setas é bloqueado, mas o arrastar não tem como na versão do primefaces utilizada pelo projeto. A ação de sucesso é apresentada mas não ocorre a alteração no banco de dados. Deverá ser corrigido em uma futura SM.

**Comment by kleiberfaria** [comment]
Item verificado!
