### ISSUE TITLE
CDU_SCM_007_Atribuir Função Eleitoral a Mesário - Lupa de pesquisa

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#87]
Prezados,

Realizando um consulta conforme imagem em anexo, ainda encontra-se inativo para a pesquisa quanto para os testes.

![1](https://cloud.githubusercontent.com/assets/9218077/5434468/5dc05192-8439-11e4-8f87-aa2d06aa74d5.gif)

**Comment by saires** [comment]
Verificar com o Haber. Ele já estava verificando.

**Comment by halvesl** [comment]
CORRIGIDO.

**Comment by kleiberfaria** [comment]
Item verificado !
