### ISSUE TITLE
CDU_SCM_004_Gerenciar Configuracao de Funcao Especial - Acesso Impossibilitado

### ISSUE THREAD

**Issue by jmatil** [islssa/SCM#88]
Após atribuir uma quantidade a uma função especial (CDU-004) e realizar a pesquisa do CDU-039, o sistema não deixa o usuário acessar novamente o menu destacado na image (CDU-004).

![issue-29](https://cloud.githubusercontent.com/assets/6584772/5436076/354fc3ae-8449-11e4-9806-1537aa7ff5aa.png)

**Comment by saires** [comment]
Corrigido. Na verdade não consegui simular esse erro.

**Comment by kleiberfaria** [comment]
Fiz o passo conforme descrição nesse Git e de fato não se consegue voltar para a navegação superior da aplicação.

![1](https://cloud.githubusercontent.com/assets/9218077/5453260/73cb36fe-850c-11e4-9199-92346c222cc0.jpg)

**Comment by kleiberfaria** [comment]
Item verificado !
