### ISSUE TITLE
CDU_SCM_039_Atribuir_Funcao_Especial_ao_Eleitor - Importar Dados de Outra Eleição

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#89]
Prezados,

Ao realizar  "Importar Dados de Outra Eleição" na aplicação, ocorre o erro conforme as imagens em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/5436804/9c49241c-8451-11e4-885c-3a4138ac1d76.jpg)

![2](https://cloud.githubusercontent.com/assets/9218077/5436807/a15be78c-8451-11e4-8c58-9ae0b247c0fa.jpg)

**Comment by saires** [comment]
Corrigido.

**Comment by kleiberfaria** [comment]
Item verificado!
