### ISSUE TITLE
CDU_SCM_002_Gerenciar Configuracao de Mesa Receptora de Votos_ Retirar a informação * Campos obrigatórios 

### ISSUE THREAD

**Issue by marasb** [islssa/SCM#9]
No caso de uso não está descrita a informação "\* Campos obrigatórios ", porém na aplicação aparece essa informação antes dos botões.
Favor retirar a informação "\* Campos obrigatórios " da tela.

**Comment by jadossantos** [comment]
Alterado.

**Comment by marasb** [comment]
Defeito corrigido.
