### ISSUE TITLE
CDU_SCM_039_Atribuir_Funcao_Especial_ao_Eleitor - MRJ

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#90]
Prezados,

Ao atribuir uma função especial na navegação no SCM, e na tela de Atribuição Função Eleitoral selecionando o [ MRJ ] conforme as imagens em anexo e realizando a pesquisa, a aplicação volta para a tela do ODIN

![1](https://cloud.githubusercontent.com/assets/9218077/5452808/bd1998a6-8506-11e4-8941-449c42fd51c7.jpg)

![2](https://cloud.githubusercontent.com/assets/9218077/5452810/c1711424-8506-11e4-9511-f7c9ff532c5e.jpg)

![3](https://cloud.githubusercontent.com/assets/9218077/5452819/c4a1cf3a-8506-11e4-8f88-2c6e7404597e.jpg)

**Comment by saires** [comment]
Esse fluxo é do UC07. Ver com o Haber.

**Comment by halvesl** [comment]
corrigido.

**Comment by kleiberfaria** [comment]
Item verificado!
