### ISSUE TITLE
CDU_SCM_002_Gerenciar_Configuracao_de_Mesa_Receptora_de_Votos - Não Recupera as funções eleitorais 

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#91]
Prezados,

Ao realizar uma Configuração de Mesa Receptora de Votos conforme a imagem, o sistema não esta trazendo as funções eleitorais. 

![1](https://cloud.githubusercontent.com/assets/9218077/5470773/fee2f9f8-85d3-11e4-823d-c2cd4bb6e006.jpg)

**Comment by saires** [comment]
Corrigido.

**Comment by kleiberfaria** [comment]
Item verificado !
