### ISSUE TITLE
CDU_SCM_002_Gerenciar_Configuração_de_Mesa_Receptora_de_Votos - Recuperar Funções Eleitorais

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#92]
Prezados,

Ao realizar o acesso no MRV para trazer as funções eleitorais, a aplicação não recupera o mesmo.

![1](https://cloud.githubusercontent.com/assets/9218077/5487932/9a2e4a00-869e-11e4-9db3-5fe4c033038b.jpg)

**Comment by saires** [comment]
Após concessão de granst no Banco de Dados a funcionalidade está funcionando normalmente.

**Comment by kleiberfaria** [comment]
Item verificado !
