### ISSUE TITLE
CDU_SCM_002_Gerenciar_Configuracao_de_Mesa_Receptora_de_Votos - Perfil TRE

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#93]
Prezados,

Para o perfil TRE, verificar quanto ao sistema recuperar configuradas para a mesa receptora ao selecionar a "Zona Eleitoral"

![4](https://cloud.githubusercontent.com/assets/9218077/5493918/441e191e-86d6-11e4-8856-20588b4a9afa.jpg)

**Comment by saires** [comment]
Corrigido.

**Comment by kleiberfaria** [comment]
Item verificado !
