### ISSUE TITLE
CDU_SCM_039_Atribuir_Função_Especial_ao_Eleitor - Quantidade de Eleitor Atribuido

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#94]
Prezados,

Conforme o fluxo, após atribuir uma função eleitoral, o sistema não está carregando a quantidade de eleitor conforme as imagens em anexo.

![1](https://cloud.githubusercontent.com/assets/9218077/5524644/dcdc7632-89bf-11e4-9f1a-751b2fcdb49d.jpg)

![2](https://cloud.githubusercontent.com/assets/9218077/5524646/e207839a-89bf-11e4-82fa-1c2843a7bdc5.jpg)

**Comment by saires** [comment]
Corrigido pelo Haber.

**Comment by kleiberfaria** [comment]
Item verificado
