### ISSUE TITLE
CDU_SCM_039_Atribuir_Função_Especial_ao_Eleitor - Erro no Campo Seção

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#95]
Prezados,

Ao realizar uma atribuição na função eleitoral e ao colocar no campo "seção" um valor ocorre o erro na tela conforme print na tela.

![atribuir_e_mrv](https://cloud.githubusercontent.com/assets/9218077/5537604/d07e5924-8a8b-11e4-857f-1bdabfd2f217.jpg)

**Comment by saires** [comment]
Esse UC é o 7. Atribuir ao Haber.

**Comment by kleiberfaria** [comment]
Realizada a atribuição !

**Comment by halvesl** [comment]
corrigido.

**Comment by kleiberfaria** [comment]
O erro ainda persiste conforme imagem em anexo.
![k](https://cloud.githubusercontent.com/assets/9218077/5557360/95bee9d6-8ce1-11e4-81cc-d7d9c653d6b8.jpg)

**Comment by halvesl** [comment]
corrigido. Aguardar próxima build.

**Comment by kleiberfaria** [comment]
Item verificado!
