### ISSUE TITLE
CDU_SCM_007_Atribuir_Funcao_Eleitoral_a_Mesario - Idade Maior Idade Menor

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#96]
Conforme imagem em anexo, a aplicação permite realizar nos campos idade mínima um número maior e idade máxima um número menor.

![valor_minimo_valor_maior](https://cloud.githubusercontent.com/assets/9218077/5538052/97353c84-8a93-11e4-92f0-6038b10fbbee.jpg)

**Comment by halvesl** [comment]
Sávio vc consegue direcionar esse erro pro usuário halvesl?

**Comment by halvesl** [comment]
corrigido

**Comment by kleiberfaria** [comment]
Item verificado !
