### ISSUE TITLE
CDU_SCM_003_Gerenciar Configuração de Mesa Receptora de Justificativa - Excluir

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#98]
Prezados,

Realizando um exclusão na tela "Configuração de Mesa Receptora de Justificativas", o sistema exibe a mensagem conforme em anexo. A aplicação mostra a soma de 17 eleitores atribuidos e a quantidade "zero" tanto para Eleitores na situação Convocado quanto para Eleitores na situação Nomeado.
![distribuicao_de_eleitores](https://cloud.githubusercontent.com/assets/9218077/5540015/a1af727c-8aae-11e4-9661-5e4a85a05a2b.jpg)

**Comment by saires** [comment]
Corrigido. Favor retestar e notificar qualquer inconsistência.

**Comment by kleiberfaria** [comment]
Item verificado !
