### ISSUE TITLE
CDU_SCM_007_Atribuir_Funcao_Eleitoral_a_Mesario - Lista de Funções Eleitorais

### ISSUE THREAD

**Issue by kleiberfaria** [islssa/SCM#99]
Ao selecionar na lista de funções eleitorais conforme imagem em anexo, a aplicação volta para a tela do ODIN.
![a1](https://cloud.githubusercontent.com/assets/9218077/5541920/0ba22770-8ac7-11e4-890c-b7a9cb50697f.jpg)

![a2](https://cloud.githubusercontent.com/assets/9218077/5541924/101226fc-8ac7-11e4-9db5-f549177e0910.jpg)

**Comment by halvesl** [comment]
corrigido! Já foi feito o deploy.

**Comment by kleiberfaria** [comment]
Item verificado !
